import { ComponentCategories, PropTypes } from '../types'
import type { ComponentMeta } from '../types'

// Data 数据展示
export const dataComponents: ComponentMeta[] = [
  {
    type: 'ea-avatar',
    name: '头像',
    category: ComponentCategories.DATA,
    icon: 'Avatar',
    props: [
      {
        name: 'icon',
        label: '图标类名',
        type: PropTypes.STRING,
        default: '',
      },
      {
        name: 'size',
        label: '尺寸',
        type: PropTypes.UNIT,
        default: 'default',
      },
      {
        name: 'shape',
        label: '形状',
        type: PropTypes.SELECT,
        default: 'circle',
        options: [
          { label: '圆形', value: 'circle' },
          { label: '方形', value: 'square' },
        ],
      },
      {
        name: 'src',
        label: '图片地址',
        type: PropTypes.STRING,
        default: '',
      },
      {
        name: 'src-set',
        label: '图片地址集',
        type: PropTypes.STRING,
        default: '',
      },
      {
        name: 'alt',
        label: '替代文本',
        type: PropTypes.STRING,
        default: '',
      },
      {
        name: 'fit',
        label: '图片适应方式',
        type: PropTypes.SELECT,
        default: 'cover',
        options: [
          { label: '填充', value: 'fill' },
          { label: '包含', value: 'contain' },
          { label: '覆盖', value: 'cover' },
          { label: '无', value: 'none' },
          { label: '缩放', value: 'scale-down' },
        ],
      },
    ],
    events: [{ name: 'error', label: '图片加载失败' }],
    slots: [{ name: 'default', label: '默认插槽' }],
    styleConfig: {
      parts: [
        {
          name: 'container',
          label: '外层容器',
          styles: ['width', 'height', 'border-radius'],
        },
      ],
    },
  },
  {
    type: 'ea-badge',
    name: '徽章',
    category: ComponentCategories.DATA,
    icon: 'Badge',
    props: [
      {
        name: 'value',
        label: '显示值',
        type: PropTypes.STRING,
        default: '',
      },
      {
        name: 'max',
        label: '最大值',
        type: PropTypes.NUMBER,
        default: null,
      },
      {
        name: 'is-dot',
        label: '小圆点',
        type: PropTypes.BOOLEAN,
        default: false,
      },
      {
        name: 'data-hidden',
        label: '隐藏',
        type: PropTypes.BOOLEAN,
        default: false,
      },
      {
        name: 'type',
        label: '类型',
        type: PropTypes.SELECT,
        default: 'danger',
        options: [
          { label: '主要', value: 'primary' },
          { label: '成功', value: 'success' },
          { label: '警告', value: 'warning' },
          { label: '危险', value: 'danger' },
          { label: '信息', value: 'info' },
        ],
      },
      {
        name: 'show-zero',
        label: '显示零值',
        type: PropTypes.BOOLEAN,
        default: true,
      },
      {
        name: 'color',
        label: '背景色',
        type: PropTypes.STRING,
        default: '',
      },
      {
        name: 'offset-x',
        label: 'X轴偏移',
        type: PropTypes.NUMBER,
        default: 0,
      },
      {
        name: 'offset-y',
        label: 'Y轴偏移',
        type: PropTypes.NUMBER,
        default: 0,
      },
    ],
    events: [],
    slots: [{ name: 'default', label: '默认插槽' }],
    styleConfig: {
      parts: [
        {
          name: 'container',
          label: '外层容器',
          styles: ['display'],
        },
        {
          name: 'content',
          label: '徽章内容',
          styles: ['background-color', 'color'],
        },
      ],
    },
  },
  {
    type: 'ea-calendar',
    name: '日历',
    category: ComponentCategories.DATA,
    icon: 'Calendar',
    props: [
      {
        name: 'value',
        label: '指定日期',
        type: PropTypes.STRING,
        default: Date.now(),
      },
      {
        name: 'controller-type',
        label: '控制器类型',
        type: PropTypes.SELECT,
        default: 'button',
        options: [
          { label: '按钮', value: 'button' },
          { label: '选择器', value: 'select' },
        ],
      },
    ],
    events: [{ name: 'select', label: '选择日期' }],
    slots: [{ name: 'header', label: '头部插槽' }],
    styleConfig: {
      parts: [
        {
          name: 'container',
          label: '外层容器',
          styles: ['background-color', 'border-color'],
        },
        {
          name: 'header',
          label: '头部容器',
          styles: ['background-color', 'border-color'],
        },
        {
          name: 'body',
          label: '主体部分',
          styles: ['background-color'],
        },
        {
          name: 'day',
          label: '日期单元格',
          styles: ['color', 'background-color'],
        },
      ],
    },
  },
  {
    type: 'ea-card',
    name: '卡片',
    category: ComponentCategories.DATA,
    icon: 'Card',
    props: [
      {
        name: 'header',
        label: '标题',
        type: PropTypes.STRING,
        default: '',
      },
      {
        name: 'footer',
        label: '页脚',
        type: PropTypes.STRING,
        default: '',
      },
      {
        name: 'shadow',
        label: '阴影',
        type: PropTypes.SELECT,
        default: 'always',
        options: [
          { label: '始终显示', value: 'always' },
          { label: '悬停显示', value: 'hover' },
          { label: '从不显示', value: 'never' },
        ],
      },
    ],
    events: [],
    slots: [
      { name: 'default', label: '卡片内容' },
      { name: 'header', label: '卡片标题' },
      { name: 'footer', label: '卡片页脚' },
    ],
    styleConfig: {
      parts: [
        {
          name: 'container',
          label: '卡片容器',
          styles: ['background-color', 'border-color', 'box-shadow'],
        },
        {
          name: 'header',
          label: '标题容器',
          styles: ['border-color', 'padding'],
        },
        {
          name: 'content',
          label: '内容容器',
          styles: ['padding'],
        },
        {
          name: 'footer',
          label: '页脚容器',
          styles: ['border-color', 'padding'],
        },
      ],
    },
  },
  {
    type: 'ea-carousel',
    name: '走马灯',
    category: ComponentCategories.DATA,
    icon: 'Carousel',
    props: [
      {
        name: 'height',
        label: '高度',
        type: PropTypes.UNIT,
        default: '300px',
      },
      {
        name: 'direction',
        label: '轮播方向',
        type: PropTypes.SELECT,
        default: 'horizontal',
        options: [
          { label: '水平', value: 'horizontal' },
          { label: '垂直', value: 'vertical' },
        ],
      },
      {
        name: 'index',
        label: '当前索引',
        type: PropTypes.NUMBER,
        default: 0,
      },
      {
        name: 'trigger',
        label: '触发方式',
        type: PropTypes.SELECT,
        default: 'hover',
        options: [
          { label: '悬停', value: 'hover' },
          { label: '点击', value: 'click' },
        ],
      },
      {
        name: 'interval',
        label: '自动播放间隔',
        type: PropTypes.NUMBER,
        default: 3000,
      },
      {
        name: 'arrow',
        label: '箭头显示时机',
        type: PropTypes.SELECT,
        default: 'hover',
        options: [
          { label: '从不', value: 'never' },
          { label: '始终', value: 'always' },
          { label: '悬停', value: 'hover' },
        ],
      },
      {
        name: 'autoplay',
        label: '自动播放',
        type: PropTypes.BOOLEAN,
        default: true,
      },
      {
        name: 'loop',
        label: '循环播放',
        type: PropTypes.BOOLEAN,
        default: true,
      },
      {
        name: 'pause-on-hover',
        label: '悬停暂停',
        type: PropTypes.BOOLEAN,
        default: true,
      },
      {
        name: 'indicator-position',
        label: '指示器位置',
        type: PropTypes.SELECT,
        default: '',
        options: [
          { label: '默认', value: ' ' },
          { label: '无', value: 'none' },
          { label: '外部', value: 'outside' },
        ],
      },
    ],
    events: [{ name: 'change', label: '索引变化' }],
    slots: [{ name: 'default', label: '轮播项插槽', isContentSlot: false }],
    childComponents: ['ea-carousel-item'],
    styleConfig: {
      parts: [
        {
          name: 'container',
          label: '外层容器',
          styles: ['width', 'height'],
        },
        {
          name: 'content',
          label: '内容容器',
          styles: ['background-color'],
        },
        {
          name: 'indicator-wrap',
          label: '指示器容器',
          styles: ['background-color'],
        },
        {
          name: 'indicator',
          label: '指示器项',
          styles: ['background-color'],
        },
      ],
    },
  },
  {
    type: 'ea-carousel-item',
    name: '走马灯项',
    category: ComponentCategories.DATA,
    icon: 'CarouselItem',
    isChildComponent: true,
    parentComponents: ['ea-carousel'],
    props: [],
    events: [],
    slots: [{ name: 'default', label: '内容插槽' }],
    styleConfig: {
      parts: [
        {
          name: 'container',
          label: '外层容器',
          styles: ['width', 'height'],
        },
      ],
    },
  },
  {
    type: 'ea-collapse',
    name: '折叠面板',
    category: ComponentCategories.DATA,
    icon: 'Collapse',
    props: [
      {
        name: 'active',
        label: '当前激活面板',
        type: PropTypes.STRING,
        default: '',
      },
      {
        name: 'accordion',
        label: '手风琴模式',
        type: PropTypes.BOOLEAN,
        default: false,
      },
      {
        name: 'expand-icon-position',
        label: '图标位置',
        type: PropTypes.SELECT,
        default: 'right',
        options: [
          { label: '左侧', value: 'left' },
          { label: '右侧', value: 'right' },
        ],
      },
    ],
    events: [{ name: 'change', label: '面板变化' }],
    slots: [{ name: 'default', label: '折叠项插槽', isContentSlot: false }],
    childComponents: ['ea-collapse-item'],
    styleConfig: {
      parts: [
        {
          name: 'container',
          label: '外层容器',
          styles: ['border-color'],
        },
      ],
    },
  },
  {
    type: 'ea-collapse-item',
    name: '折叠面板项',
    category: ComponentCategories.DATA,
    icon: 'CollapseItem',
    isChildComponent: true,
    parentComponents: ['ea-collapse'],
    props: [
      {
        name: 'title',
        label: '面板标题',
        type: PropTypes.STRING,
        default: '',
      },
      {
        name: 'name',
        label: '唯一标识',
        type: PropTypes.STRING,
        default: '',
      },
      {
        name: 'disabled',
        label: '禁用',
        type: PropTypes.BOOLEAN,
        default: false,
      },
    ],
    events: [],
    slots: [
      { name: 'default', label: '内容插槽' },
      { name: 'title', label: '标题插槽' },
    ],
    styleConfig: {
      parts: [
        {
          name: 'container',
          label: '外层容器',
          styles: ['border-color'],
        },
      ],
    },
  },
  {
    type: 'ea-descriptions',
    name: '描述列表',
    category: ComponentCategories.DATA,
    icon: 'Descriptions',
    childComponents: ['ea-descriptions-item'],
    props: [
      {
        name: 'title',
        label: '标题',
        type: PropTypes.STRING,
        default: '',
      },
      {
        name: 'direction',
        label: '排列方向',
        type: PropTypes.SELECT,
        default: 'horizontal',
        options: [
          { label: '水平', value: 'horizontal' },
          { label: '垂直', value: 'vertical' },
        ],
      },
      {
        name: 'border',
        label: '边框',
        type: PropTypes.BOOLEAN,
        default: false,
      },
      {
        name: 'column',
        label: '列数',
        type: PropTypes.NUMBER,
        default: 3,
      },
      {
        name: 'size',
        label: '尺寸',
        type: PropTypes.SELECT,
        default: 'default',
        options: [
          { label: '大', value: 'large' },
          { label: '中', value: 'default' },
          { label: '小', value: 'small' },
        ],
      },
      {
        name: 'label-width',
        label: '标签宽度',
        type: PropTypes.UNIT,
        default: '',
      },
    ],
    events: [],
    slots: [
      { name: 'default', label: '默认插槽' },
      { name: 'title', label: '标题插槽' },
      { name: 'extra', label: '额外操作区插槽' },
    ],
    styleConfig: {
      parts: [
        {
          name: 'container',
          label: '外层容器',
          styles: ['background-color'],
        },
        {
          name: 'caption',
          label: '标题与操作区容器',
          styles: ['background-color', 'padding'],
        },
        {
          name: 'title',
          label: '标题区域',
          styles: ['color', 'font-size'],
        },
        {
          name: 'extra',
          label: '额外操作区',
          styles: ['background-color'],
        },
        {
          name: 'body',
          label: '表格主体',
          styles: ['background-color'],
        },
        {
          name: 'row',
          label: '行',
          styles: ['background-color'],
        },
        {
          name: 'col-cell',
          label: '单元格',
          styles: ['background-color', 'padding'],
        },
        {
          name: 'label',
          label: '标签单元格',
          styles: ['background-color', 'color', 'font-weight'],
        },
        {
          name: 'content',
          label: '内容单元格',
          styles: ['background-color', 'color'],
        },
        {
          name: 'cell',
          label: '通用单元格',
          styles: ['background-color', 'padding'],
        },
      ],
    },
  },
  {
    type: 'ea-descriptions-item',
    name: '描述列表项',
    category: ComponentCategories.DATA,
    icon: 'Document',
    isChildComponent: true,
    parentComponents: ['ea-descriptions'],
    props: [
      {
        name: 'label',
        label: '标签文本',
        type: PropTypes.STRING,
        default: '',
      },
      {
        name: 'children',
        label: '内容',
        type: PropTypes.STRING,
        default: '',
      },
      {
        name: 'colspan',
        label: '跨列数',
        type: PropTypes.NUMBER,
        default: 1,
      },
      {
        name: 'rowspan',
        label: '跨行数',
        type: PropTypes.NUMBER,
        default: 1,
      },
      {
        name: 'align',
        label: '对齐方式',
        type: PropTypes.SELECT,
        default: '',
        options: [
          { label: '左对齐', value: 'left' },
          { label: '居中', value: 'center' },
          { label: '右对齐', value: 'right' },
        ],
      },
      {
        name: 'label-align',
        label: '标签对齐',
        type: PropTypes.SELECT,
        default: '',
        options: [
          { label: '左对齐', value: 'left' },
          { label: '居中', value: 'center' },
          { label: '右对齐', value: 'right' },
        ],
      },
      {
        name: 'width',
        label: '单元格宽度',
        type: PropTypes.UNIT,
        default: '',
      },
      {
        name: 'label-width',
        label: '标签宽度',
        type: PropTypes.UNIT,
        default: '',
      },
      {
        name: 'label-part',
        label: '标签 Part',
        type: PropTypes.STRING,
        default: '',
      },
      {
        name: 'content-part',
        label: '内容 Part',
        type: PropTypes.STRING,
        default: '',
      },
    ],
    events: [],
    slots: [{ name: 'default', label: '默认插槽' }],
    styleConfig: {
      parts: [
        {
          name: 'container',
          label: '外层容器',
          styles: ['background-color'],
        },
      ],
    },
  },
  {
    type: 'ea-empty',
    name: '空状态',
    category: ComponentCategories.DATA,
    icon: 'Empty',
    props: [
      {
        name: 'description',
        label: '描述',
        type: PropTypes.STRING,
        default: '',
      },
      {
        name: 'image',
        label: '图片',
        type: PropTypes.STRING,
        default: '',
      },
      {
        name: 'image-size',
        label: '图片大小',
        type: PropTypes.UNIT,
        default: '80px',
      },
    ],
    events: [],
    slots: [
      { name: 'default', label: '默认插槽' },
      { name: 'image', label: '图片插槽' },
      { name: 'description', label: '描述插槽' },
    ],
    styleConfig: {
      parts: [
        {
          name: 'container',
          label: '外层容器',
          styles: ['display', 'padding'],
        },
        {
          name: 'placeholder',
          label: '图片容器',
          styles: ['width', 'height'],
        },
        {
          name: 'description',
          label: '描述容器',
          styles: ['color'],
        },
        {
          name: 'bottom',
          label: '底部容器',
          styles: ['margin-top'],
        },
      ],
    },
  },
  {
    type: 'ea-image',
    name: '图片',
    category: ComponentCategories.DATA,
    icon: 'Image',
    props: [
      {
        name: 'src',
        label: '图片地址',
        type: PropTypes.STRING,
        default: '',
      },
      {
        name: 'fit',
        label: '适应方式',
        type: PropTypes.SELECT,
        default: 'cover',
        options: [
          { label: '填充', value: 'fill' },
          { label: '包含', value: 'contain' },
          { label: '覆盖', value: 'cover' },
          { label: '无', value: 'none' },
          { label: '缩放', value: 'scale-down' },
        ],
      },
      {
        name: 'alt',
        label: '替代文本',
        type: PropTypes.STRING,
        default: '',
      },
      {
        name: 'width',
        label: '图片宽度',
        type: PropTypes.UNIT,
        default: '100%',
      },
      {
        name: 'height',
        label: '图片高度',
        type: PropTypes.UNIT,
        default: '100%',
      },
      {
        name: 'loading',
        label: '加载方式',
        type: PropTypes.SELECT,
        default: 'eager',
        options: [
          { label: '立即加载', value: 'eager' },
          { label: '懒加载', value: 'lazy' },
        ],
      },
      {
        name: 'lazy',
        label: '懒加载（兼容模式）',
        type: PropTypes.BOOLEAN,
        default: false,
      },
      {
        name: 'referrerpolicy',
        label: '引用策略',
        type: PropTypes.SELECT,
        default: '',
        options: [
          { label: '默认', value: '' },
          { label: '不发送', value: 'no-referrer' },
          { label: '发送域名', value: 'origin' },
          { label: '不发送Referer头', value: 'unsafe-url' },
        ],
      },
      {
        name: 'crossorigin',
        label: '跨域设置',
        type: PropTypes.SELECT,
        default: '',
        options: [
          { label: '默认', value: '' },
          { label: '匿名', value: 'anonymous' },
          { label: '使用凭证', value: 'use-credentials' },
        ],
      },
      {
        name: 'preview',
        label: '开启预览',
        type: PropTypes.BOOLEAN,
        default: false,
      },
      {
        name: 'previewSrcList',
        label: '预览图列表',
        type: PropTypes.ARRAY,
        default: [],
      },
      {
        name: 'hide-on-click-modal',
        label: '预览时点击遮罩是否隐藏',
        type: PropTypes.BOOLEAN,
        default: false,
      },
      {
        name: 'initial-index',
        label: '初始预览索引',
        type: PropTypes.NUMBER,
        default: 0,
      },
      {
        name: 'z-index',
        label: '预览遮罩层级',
        type: PropTypes.NUMBER,
        default: 2000,
      },
      {
        name: 'close-on-press-escape',
        label: 'ESC键关闭预览',
        type: PropTypes.BOOLEAN,
        default: true,
      },
      {
        name: 'infinite',
        label: '无限循环预览',
        type: PropTypes.BOOLEAN,
        default: true,
      },
      {
        name: 'zoom-rate',
        label: '缩放速率',
        type: PropTypes.NUMBER,
        default: 1.2,
      },
      {
        name: 'scale',
        label: '初始缩放比例',
        type: PropTypes.NUMBER,
        default: 1,
      },
      {
        name: 'min-scale',
        label: '最小缩放比例',
        type: PropTypes.NUMBER,
        default: 0.2,
      },
      {
        name: 'max-scale',
        label: '最大缩放比例',
        type: PropTypes.NUMBER,
        default: 7,
      },
      {
        name: 'show-progress',
        label: '显示进度',
        type: PropTypes.BOOLEAN,
        default: false,
      },
    ],
    events: [
      { name: 'load', label: '加载成功' },
      { name: 'error', label: '加载失败' },
    ],
    slots: [
      { name: 'placeholder', label: '占位插槽' },
      { name: 'error', label: '错误插槽' },
      { name: 'toolbar', label: '工具栏插槽' },
      { name: 'progress', label: '进度插槽' },
    ],
    styleConfig: {
      parts: [
        {
          name: 'container',
          label: '外层容器',
          styles: ['width', 'height'],
        },
        {
          name: 'image',
          label: '图片内容',
          styles: [],
        },
        {
          name: 'error',
          label: '错误显示',
          styles: [],
        },
        {
          name: 'placeholder',
          label: '占位内容',
          styles: [],
        },
        {
          name: 'preview',
          label: '预览容器',
          styles: [],
        },
      ],
      cssVariables: [
        {
          name: '--ea-image-width',
          label: '图片宽度',
          type: 'length',
          default: '100%',
        },
        {
          name: '--ea-image-height',
          label: '图片高度',
          type: 'length',
          default: '100%',
        },
        {
          name: '--ea-image-fit',
          label: '图片适应方式',
          type: 'select',
          default: 'inherit',
          options: ['inherit', 'fill', 'contain', 'cover', 'none', 'scale-down'],
        },
        {
          name: '--ea-image-background',
          label: '背景颜色',
          type: 'color',
          default: 'var(--grey-100)',
        },
      ],
    },
  },
  {
    type: 'ea-pagination',
    name: '分页',
    category: ComponentCategories.DATA,
    icon: 'Pagination',
    props: [
      {
        name: 'total',
        label: '总条数',
        type: PropTypes.NUMBER,
        default: 0,
      },
      {
        name: 'pager-count',
        label: '最大页码按钮数',
        type: PropTypes.NUMBER,
        default: 7,
      },
      {
        name: 'layout',
        label: '布局',
        type: PropTypes.MULTI_SELECT,
        default: ['prev', 'pager', 'next', 'jumper', '->', 'total'],
        options: [
          { value: 'prev', label: '上一页按钮' },
          { value: 'pager', label: '页码列表' },
          { value: 'next', label: '下一页按钮' },
          { value: '->', label: '右对齐分隔符' },
          { value: 'jumper', label: '跳转输入框' },
          { value: 'total', label: '总条目数' },
          { value: 'sizes', label: '每页条数选择器' },
        ],
      },
      {
        name: 'background',
        label: '带背景样式',
        type: PropTypes.BOOLEAN,
        default: false,
      },
      {
        name: 'default-page-size',
        label: '默认每页显示条数',
        type: PropTypes.NUMBER,
        default: 10,
      },
      {
        name: 'pageSizes',
        label: '每页显示条数',
        type: PropTypes.ARRAY,
        default: 10,
      },
      {
        name: 'currentPage',
        label: '当前页码',
        type: PropTypes.NUMBER,
        default: 1,
      },
      {
        name: 'hide-on-single-page',
        label: '单页时隐藏',
        type: PropTypes.BOOLEAN,
        default: false,
      },
      {
        name: 'size',
        label: '尺寸',
        type: PropTypes.SELECT,
        default: 'default',
        options: [
          {
            label: '大',
            value: 'large',
          },
          {
            label: '默认',
            value: 'default',
          },
          {
            label: '小',
            value: 'small',
          },
        ],
      },
      {
        name: 'disabled',
        label: '禁用',
        type: PropTypes.BOOLEAN,
        default: false,
      },
    ],
    events: [
      {
        name: 'change',
        label: '页码改变事件',
        params: '{ currentPage: number, pageSize: number }',
      },
      { name: 'ea-size-change', label: '每页条数改变事件', params: '{ pageSize: number }' },
      { name: 'ea-current-change', label: '当前页改变事件', params: '{ value: number }' },
      { name: 'ea-prev-click', label: '点击上一页事件', params: '{ value: number }' },
      { name: 'ea-next-click', label: '点击下一页事件', params: '{ value: number }' },
    ],
    slots: [],
    styleConfig: {
      parts: [
        { name: 'container', label: '组件根容器', description: '用于整体样式定制' },
        { name: 'pager', label: '页码列表容器', description: '仅在 layout 包含 pager 时存在' },
        { name: 'page', label: '单个页码按钮' },
        { name: 'more', label: '省略号/更多按钮' },
        { name: 'prev-icon', label: '上一页箭头图标' },
        { name: 'next-icon', label: '下一页箭头图标' },
        { name: 'total', label: '总数显示容器', description: '当 layout 包含 total 时存在' },
        { name: 'jumper-wrap', label: '跳转输入容器', description: '当 layout 包含 jumper 时存在' },
        { name: 'jumper', label: '跳转输入控件', description: '对应内部 ea-input' },
        { name: 'sizes', label: '每页大小选择控件', description: '当 layout 包含 sizes 时存在' },
        { name: 'separator', label: '右对齐分隔占位', description: '对应 -> 在 layout 中的位置' },
      ],
    },
  },
  {
    type: 'ea-progress',
    name: '进度条',
    category: ComponentCategories.DATA,
    icon: 'Progress',
    props: [
      {
        name: 'percentage',
        label: '进度百分比',
        type: PropTypes.NUMBER,
        default: 0,
      },
      {
        name: 'type',
        label: '进度条类型',
        type: PropTypes.SELECT,
        default: 'line',
        options: [
          { label: '线性', value: 'line' },
          { label: '圆环', value: 'circle' },
          { label: '仪表盘', value: 'dashboard' },
        ],
      },
      {
        name: 'stroke-width',
        label: '进度条宽度',
        type: PropTypes.UNIT,
        default: '8px',
      },
      {
        name: 'text-inside',
        label: '文字内置',
        type: PropTypes.BOOLEAN,
        default: false,
      },
      {
        name: 'status',
        label: '状态',
        type: PropTypes.SELECT,
        default: ' ',
        options: [
          { label: '默认', value: ' ' },
          { label: '成功', value: 'success' },
          { label: '警告', value: 'warning' },
          { label: '异常', value: 'exception' },
        ],
      },
      {
        name: 'indeterminate',
        label: '动画进度条',
        type: PropTypes.BOOLEAN,
        default: false,
      },
      {
        name: 'duration',
        label: '动画持续时间',
        type: PropTypes.NUMBER,
        default: 3,
      },
      {
        name: 'color',
        label: '进度条颜色',
        type: PropTypes.STRING,
        default: '',
      },
      {
        name: 'striped',
        label: '条纹样式',
        type: PropTypes.BOOLEAN,
        default: false,
      },
      {
        name: 'striped-flow',
        label: '条纹流动',
        type: PropTypes.BOOLEAN,
        default: false,
      },
      {
        name: 'show-text',
        label: '显示文字',
        type: PropTypes.BOOLEAN,
        default: true,
      },
      {
        name: 'size',
        label: '进度条大小',
        type: PropTypes.UNIT,
        default: '126px',
      },
    ],
    events: [{ name: 'change', label: '进度变化' }],
    slots: [
      {
        name: 'default',
        label: '默认插槽',
        slotScope: [{ name: 'percentage', label: '百分比值' }],
      },
    ],
    styleConfig: {
      parts: [
        {
          name: 'container',
          label: '组件根元素',
          styles: ['width'],
        },
        {
          name: 'track',
          label: '外层轨道',
          styles: ['background-color'],
        },
        {
          name: 'path',
          label: '进度路径',
          styles: ['background-color'],
        },
        {
          name: 'percentage',
          label: '文本容器/插槽外层',
          styles: ['color'],
        },
        {
          name: 'status-icon',
          label: '状态图标',
          styles: ['color', 'font-size'],
        },
      ],
    },
  },
  {
    type: 'ea-result',
    name: '结果',
    category: ComponentCategories.DATA,
    icon: 'Result',
    props: [
      {
        name: 'title',
        label: '标题',
        type: PropTypes.STRING,
        default: '',
      },
      {
        name: 'sub-title',
        label: '副标题',
        type: PropTypes.STRING,
        default: '',
      },
      {
        name: 'type',
        label: '类型',
        type: PropTypes.SELECT,
        default: 'primary',
        options: [
          { label: '主要', value: 'primary' },
          { label: '成功', value: 'success' },
          { label: '警告', value: 'warning' },
          { label: '信息', value: 'info' },
          { label: '错误', value: 'error' },
        ],
      },
      {
        name: 'icon',
        label: '图标类型',
        type: PropTypes.STRING,
        default: '',
      },
    ],
    events: [],
    slots: [
      { name: 'icon', label: '图标内容' },
      { name: 'title', label: '标题内容' },
      { name: 'sub-title', label: '副标题内容' },
      { name: 'extra', label: '额外内容' },
    ],
    styleConfig: {
      parts: [
        {
          name: 'container',
          label: '外层容器',
          styles: ['background-color', 'padding'],
        },
        {
          name: 'icon-wrap',
          label: '图标容器',
          styles: ['background-color', 'padding'],
        },
        {
          name: 'icon',
          label: '图标',
          styles: ['color', 'font-size'],
        },
        {
          name: 'title',
          label: '标题容器',
          styles: ['color', 'font-size'],
        },
        {
          name: 'subTitle-wrap',
          label: '描述容器',
          styles: ['color', 'font-size'],
        },
        {
          name: 'extra-wrap',
          label: '额外内容容器',
          styles: ['padding', 'margin'],
        },
      ],
    },
  },
  {
    type: 'ea-segmented',
    name: '分段控制器',
    category: ComponentCategories.DATA,
    icon: 'Segmented',
    props: [
      {
        name: 'name',
        label: '名称',
        type: PropTypes.STRING,
        default: '',
      },
      {
        name: 'value',
        label: '选中值',
        type: PropTypes.STRING,
        default: '',
      },
      {
        name: 'options',
        label: '选项',
        type: PropTypes.ARRAY,
        default: [],
      },
      {
        name: 'propsConfiguration',
        label: '选项字段映射',
        type: PropTypes.OBJECT,
        default: { label: 'label', value: 'value', disabled: 'disabled' },
      },
      {
        name: 'size',
        label: '尺寸',
        type: PropTypes.SELECT,
        default: 'default',
        options: [
          { label: '大', value: 'large' },
          { label: '中', value: 'default' },
          { label: '小', value: 'small' },
        ],
      },
      {
        name: 'block',
        label: '块级宽度',
        type: PropTypes.BOOLEAN,
        default: false,
      },
      {
        name: 'direction',
        label: '排列方向',
        type: PropTypes.SELECT,
        default: 'horizontal',
        options: [
          { label: '水平', value: 'horizontal' },
          { label: '垂直', value: 'vertical' },
        ],
      },
      {
        name: 'disabled',
        label: '禁用',
        type: PropTypes.BOOLEAN,
        default: false,
      },
    ],
    events: [{ name: 'change', label: '选中改变' }],
    slots: [{ name: 'default', label: '默认插槽' }],
    styleConfig: {
      parts: [
        {
          name: 'container',
          label: '外层容器',
          styles: ['background-color', 'border-color'],
        },
        {
          name: 'item',
          label: '选项容器',
          styles: ['background-color', 'color'],
        },
        {
          name: 'label',
          label: '选项标签',
          styles: ['color', 'font-size'],
        },
        {
          name: 'input',
          label: '原生输入框',
          styles: [],
        },
        {
          name: 'indicator',
          label: '选中指示器',
          styles: ['background-color'],
        },
      ],
    },
  },
  {
    type: 'ea-skeleton',
    name: '骨架屏',
    category: ComponentCategories.DATA,
    icon: 'Skeleton',
    props: [
      {
        name: 'loading',
        label: '加载中',
        description: {
          type: 'ea-text',
          content: '可以切换 实际 DOM 内容 与 骨架屏模板',
        },
        type: PropTypes.BOOLEAN,
        default: true,
      },
      {
        name: 'animated',
        label: '动画',
        type: PropTypes.BOOLEAN,
        default: false,
      },
      {
        name: 'rows',
        label: '行数',
        type: PropTypes.NUMBER,
        default: 4,
      },
      {
        name: 'throttle-leading',
        label: '节流延迟(开始)（单位：ms）',
        type: PropTypes.NUMBER,
        default: 0,
      },
      {
        name: 'throttle-trailing',
        label: '节流延迟(结束)（单位：ms）',
        type: PropTypes.NUMBER,
        default: 0,
      },
    ],
    events: [],
    slots: [
      { name: 'default', label: '默认插槽' },
      { name: 'template', label: '模板插槽' },
    ],
    styleConfig: {
      parts: [
        {
          name: 'container',
          label: '外层容器',
          styles: ['background-color'],
        },
      ],
    },
  },
  {
    type: 'ea-skeleton-item',
    name: '骨架屏项',
    category: ComponentCategories.DATA,
    icon: 'SkeletonItem',
    isChildComponent: true,
    parentComponents: ['ea-skeleton'],
    props: [
      {
        name: 'variant',
        label: '变体',
        type: PropTypes.SELECT,
        default: 'p',
        options: [
          { label: '段落', value: 'p' },
          { label: '文本', value: 'text' },
          { label: '标题1', value: 'h1' },
          { label: '标题3', value: 'h3' },
          { label: '说明文字', value: 'caption' },
          { label: '按钮', value: 'button' },
          { label: '图片', value: 'image' },
          { label: '圆形', value: 'circle' },
          { label: '矩形', value: 'rect' },
        ],
      },
    ],
    events: [],
    slots: [{ name: 'default', label: '默认插槽' }],
    styleConfig: {
      parts: [
        {
          name: 'container',
          label: '外层容器',
          styles: ['background-color'],
        },
      ],
    },
  },
  {
    type: 'ea-statistic',
    name: '统计组件',
    category: ComponentCategories.DATA,
    icon: 'Statistic',
    props: [
      {
        name: 'title',
        label: '标题',
        type: PropTypes.STRING,
        default: '',
      },
      {
        name: 'value',
        label: '数值',
        type: PropTypes.NUMBER,
        default: 0,
      },
    ],
    events: [],
    slots: [
      { name: 'default', label: '默认插槽' },
      { name: 'title', label: '标题插槽' },
      { name: 'prefix', label: '前缀插槽' },
      { name: 'suffix', label: '后缀插槽' },
    ],
    styleConfig: {
      parts: [
        {
          name: 'container',
          label: '组件根容器',
          styles: ['background-color'],
        },
        {
          name: 'title',
          label: '标题区域',
          styles: ['color', 'font-size'],
        },
        {
          name: 'content',
          label: '内容区域',
          styles: ['color', 'font-size'],
        },
        {
          name: 'prefix',
          label: '前缀',
          styles: ['color', 'font-size'],
        },
        {
          name: 'number',
          label: '数值区域',
          styles: ['color', 'font-size', 'font-weight'],
        },
        {
          name: 'suffix',
          label: '后缀',
          styles: ['color', 'font-size'],
        },
      ],
    },
  },
  {
    type: 'ea-countdown',
    name: '倒计时',
    category: ComponentCategories.DATA,
    icon: 'Clock',
    props: [
      {
        name: 'title',
        label: '标题',
        type: PropTypes.STRING,
        default: '',
      },
      {
        name: 'value',
        label: '倒计时目标',
        type: PropTypes.TIME,
        default: '1m',
      },
      {
        name: 'format',
        label: '显示格式',
        type: PropTypes.STRING,
        default: 'HH:mm:ss',
      },
      {
        name: 'refresh-interval',
        label: '刷新间隔(ms)',
        type: PropTypes.NUMBER,
        default: 1000,
      },
    ],
    events: [
      { name: 'change', label: '倒计时变化' },
      { name: 'ea-finish', label: '倒计时结束' },
    ],
    slots: [
      { name: 'default', label: '默认插槽' },
      { name: 'title', label: '标题插槽' },
      { name: 'prefix', label: '前缀插槽' },
      { name: 'suffix', label: '后缀插槽' },
    ],
    styleConfig: {
      parts: [
        {
          name: 'container',
          label: '组件根容器',
          styles: ['background-color'],
        },
        {
          name: 'title',
          label: '标题区域',
          styles: ['color', 'font-size'],
        },
        {
          name: 'content',
          label: '内容区域',
          styles: ['color', 'font-size'],
        },
        {
          name: 'prefix',
          label: '前缀',
          styles: ['color', 'font-size'],
        },
        {
          name: 'number',
          label: '数值区域',
          styles: ['color', 'font-size', 'font-weight'],
        },
        {
          name: 'suffix',
          label: '后缀',
          styles: ['color', 'font-size'],
        },
      ],
    },
  },
  {
    type: 'ea-table',
    name: '表格',
    category: ComponentCategories.DATA,
    icon: 'Table',
    props: [
      {
        name: 'data',
        label: '表格数据',
        type: PropTypes.ARRAY,
        default: [],
      },
      {
        name: 'stripe',
        label: '斑马纹',
        type: PropTypes.BOOLEAN,
        default: false,
      },
      {
        name: 'border',
        label: '边框',
        type: PropTypes.BOOLEAN,
        default: false,
      },
      {
        name: 'height',
        label: '高度',
        type: PropTypes.STRING,
        default: '',
      },
      {
        name: 'max-height',
        label: '最大高度',
        type: PropTypes.STRING,
        default: '',
      },
      {
        name: 'highlight-current-row',
        label: '高亮当前行',
        type: PropTypes.BOOLEAN,
        default: false,
      },
      {
        name: 'show-summary',
        label: '显示合计行',
        type: PropTypes.BOOLEAN,
        default: false,
      },
    ],
    events: [
      {
        name: 'ea-select',
        label: '选择某一行',
        params: 'event.detail: { selection: any[], row: any }',
      },
      { name: 'ea-select-all', label: '全选', params: 'event.detail: { selection: any[] }' },
      {
        name: 'ea-selection-change',
        label: '多选变化',
        params: 'event.detail: { newSelection: any[] }',
      },
      {
        name: 'ea-cell-mouse-enter',
        label: '单元格鼠标进入',
        params: 'event.detail: { row: any, column: string, cell: HTMLTableCellElement }',
      },
      {
        name: 'ea-cell-mouse-leave',
        label: '单元格鼠标离开',
        params: 'event.detail: { row: any, column: string, cell: HTMLTableCellElement }',
      },
      {
        name: 'ea-cell-click',
        label: '单元格点击',
        params: 'event.detail: { cell: HTMLTableCellElement, column: string, row: any }',
      },
      {
        name: 'ea-template-cell-click',
        label: '自定义模板单元格点击',
        params:
          'event.detail: { target: HTMLElement, rowData: any, rowIndex: number, originalEvent: MouseEvent }',
      },
      {
        name: 'ea-cell-dblclick',
        label: '单元格双击',
        params: 'event.detail: { cell: HTMLTableCellElement, column: string, row: any }',
      },
      {
        name: 'ea-cell-contextmenu',
        label: '单元格右键',
        params: 'event.detail: { cell: HTMLTableCellElement, column: string, row: any }',
      },
      {
        name: 'ea-row-click',
        label: '行点击',
        params: 'event.detail: { target: HTMLTableRowElement, column: string, row: any }',
      },
      {
        name: 'ea-row-dblclick',
        label: '行双击',
        params: 'event.detail: { target: HTMLTableRowElement, column: string, row: any }',
      },
      {
        name: 'ea-row-contextmenu',
        label: '行右键',
        params: 'event.detail: { target: HTMLTableRowElement, column: string, row: any }',
      },
      {
        name: 'ea-header-click',
        label: '表头点击',
        params: 'event.detail: { cell: HTMLTableCellElement, column: string }',
      },
      {
        name: 'ea-header-contextmenu',
        label: '表头右键',
        params: 'event.detail: { cell: HTMLTableCellElement, column: string }',
      },
      {
        name: 'ea-sort-change',
        label: '排序变化',
        params: 'event.detail: { prop: string, order: "ascend" | "descend" }',
      },
      {
        name: 'ea-current-change',
        label: '当前行变化',
        params: 'event.detail: { target: HTMLTableRowElement, column: string, row: any }',
      },
      { name: 'ea-table-data-rendered', label: '数据渲染完成', params: '-' },
    ],
    slots: [
      { name: 'default', label: '列定义插槽', description: '仅支持 ea-table-column' },
      { name: 'header', label: '表格外头部插槽' },
      { name: 'empty', label: '空数据插槽', description: '表格无数据时显示' },
    ],
    childComponents: ['ea-table-column'],
    styleConfig: {
      parts: [
        {
          name: 'container',
          label: '外层容器',
          description: '整个表格容器',
          styles: ['width'],
        },
        {
          name: 'colgroup',
          label: '表格列组',
          description: '表格列（colgroup）部分',
        },
        {
          name: 'col',
          label: '表格列',
          description: '表格列（col）部分',
        },
        {
          name: 'thead',
          label: '表头',
          description: '表格头部（thead）部分',
          styles: ['background-color', 'color'],
        },
        {
          name: 'thead-tr',
          label: '表头行',
          description: '表格头部行（tr）部分',
        },
        {
          name: 'thead-th',
          label: '表头单元格',
          description: '表格头部列（th）部分',
        },
        {
          name: 'checkbox',
          label: '复选框',
          description: '表格复选框，当存在 type="selection" 的列时有效',
        },
        {
          name: 'asc-icon',
          label: '升序图标',
          description: '表格排序图标，当存在 sortable="true" 的列时有效',
        },
        {
          name: 'desc-icon',
          label: '降序图标',
          description: '表格排序图标，当存在 sortable="true" 的列时有效',
        },
        {
          name: 'tbody',
          label: '表体',
          description: '表格主体（tbody）部分',
          styles: ['background-color'],
        },
        {
          name: 'tbody-tr',
          label: '表格行',
          description: '表格行（tr）部分',
          styles: ['background-color'],
        },
        {
          name: 'tbody-td',
          label: '表格单元格',
          description: '表格单元格（td）部分',
          styles: ['border-color', 'padding'],
        },
        {
          name: 'tfoot',
          label: '表尾',
          description: '表格尾部（tfoot）部分',
        },
        {
          name: 'tfoot-tr',
          label: '表尾行',
          description: '表格尾部行（tr）部分',
        },
        {
          name: 'tfoot-td',
          label: '表尾单元格',
          description: '表格尾部单元格（td）部分',
        },
      ],
    },
  },
  {
    type: 'ea-table-column',
    name: '表格列',
    category: ComponentCategories.DATA,
    icon: 'TableColumn',
    isChildComponent: true,
    parentComponents: ['ea-table'],
    props: [
      {
        name: 'label',
        label: '表头标题',
        type: PropTypes.STRING,
        default: '',
      },
      {
        name: 'prop',
        label: '字段名',
        type: PropTypes.STRING,
        default: '',
      },
      {
        name: 'type',
        label: '列类型',
        type: PropTypes.SELECT,
        default: '',
        options: [
          { label: '选择', value: 'selection' },
          { label: '索引', value: 'index' },
        ],
      },
      {
        name: 'align',
        label: '对齐方式',
        type: PropTypes.SELECT,
        default: 'left',
        options: [
          { label: '左对齐', value: 'left' },
          { label: '居中', value: 'center' },
          { label: '右对齐', value: 'right' },
        ],
      },
      {
        name: 'width',
        label: '列宽',
        type: PropTypes.UNIT,
        default: '',
      },
      {
        name: 'sortable',
        label: '可排序',
        type: PropTypes.BOOLEAN,
        default: false,
      },
      {
        name: 'fixed',
        label: '固定列',
        type: PropTypes.SELECT,
        default: 'false',
        options: [
          { label: '无', value: 'false' },
          { label: '左', value: 'left' },
          { label: '右', value: 'right' },
        ],
      },
    ],
    events: [],
    slots: [
      { name: 'default', label: '默认插槽', description: '用于自定义列内容' },
      { name: 'header', label: '表头插槽', description: '用于自定义表头内容' },
    ],
    styleConfig: {
      parts: [],
    },
  },
  {
    type: 'ea-tag',
    name: '标签',
    category: ComponentCategories.DATA,
    icon: 'Tag',
    props: [
      {
        name: 'children',
        label: '标签内容',
        type: PropTypes.STRING,
        default: '',
      },
      {
        name: 'type',
        label: '主题类型',
        type: PropTypes.SELECT,
        default: 'primary',
        options: [
          { label: '主要', value: 'primary' },
          { label: '成功', value: 'success' },
          { label: '信息', value: 'info' },
          { label: '警告', value: 'warning' },
          { label: '危险', value: 'danger' },
        ],
      },
      {
        name: 'size',
        label: '尺寸',
        type: PropTypes.SELECT,
        default: 'default',
        options: [
          { label: '大', value: 'large' },
          { label: '中', value: 'default' },
          { label: '小', value: 'small' },
        ],
      },
      {
        name: 'effect',
        label: '主题效果',
        type: PropTypes.SELECT,
        default: 'light',
        options: [
          { label: '深色', value: 'dark' },
          { label: '浅色', value: 'light' },
          { label: '朴素', value: 'plain' },
        ],
      },
      {
        name: 'closable',
        label: '可关闭',
        type: PropTypes.BOOLEAN,
        default: false,
      },
      {
        name: 'color',
        label: '自定义颜色',
        type: PropTypes.COLOR,
        default: '',
      },
      {
        name: 'round',
        label: '圆角',
        type: PropTypes.BOOLEAN,
        default: false,
      },
      {
        name: 'disable-transitions',
        label: '禁用过渡',
        type: PropTypes.BOOLEAN,
        default: false,
      },
    ],
    events: [
      {
        name: 'ea-remove',
        label: '标签移除',
        params: 'event: (被移除标签的相关信息，可包含 value)',
      },
    ],
    slots: [{ name: 'default', label: '默认插槽', description: '用于放置标签文本或自定义内容' }],
    styleConfig: {
      parts: [
        {
          name: 'container',
          label: 'Tag根容器',
          description: '包含文本与可选图标/关闭按钮',
          styles: ['background-color', 'color', 'border-color'],
        },
        {
          name: 'close-icon',
          label: '关闭图标',
          description: '关闭图标按钮',
          styles: ['color'],
        },
      ],
    },
  },
  {
    type: 'ea-check-tag',
    name: '可选标签',
    category: ComponentCategories.DATA,
    icon: 'CheckTag',
    props: [
      {
        name: 'children',
        label: '标签内容',
        type: PropTypes.STRING,
        default: '',
      },
      {
        name: 'type',
        label: '主题类型',
        type: PropTypes.SELECT,
        default: 'primary',
        options: [
          { label: '主要', value: 'primary' },
          { label: '成功', value: 'success' },
          { label: '信息', value: 'info' },
          { label: '警告', value: 'warning' },
          { label: '危险', value: 'danger' },
        ],
      },
      {
        name: 'checked',
        label: '选中状态',
        type: PropTypes.BOOLEAN,
        default: false,
      },
      {
        name: 'disabled',
        label: '禁用',
        type: PropTypes.BOOLEAN,
        default: false,
      },
    ],
    events: [{ name: 'change', label: '状态改变', params: 'event.detail: { checked: boolean }' }],
    slots: [{ name: 'default', label: '默认插槽', description: '用于放置标签文本或自定义内容' }],
    styleConfig: {
      parts: [
        {
          name: 'container',
          label: 'CheckTag根容器',
          description: '包含可选图标与文本',
          styles: ['background-color', 'color', 'border-color'],
        },
      ],
    },
  },
  {
    type: 'ea-timeline',
    name: '时间线',
    category: ComponentCategories.DATA,
    icon: 'Timeline',
    props: [],
    events: [],
    slots: [{ name: 'default', label: '时间线项插槽', isContentSlot: false }],
    childComponents: ['ea-timeline-item'],
    styleConfig: {
      parts: [
        {
          name: 'container',
          label: '外层容器',
          styles: ['background-color'],
        },
      ],
    },
  },
  {
    type: 'ea-timeline-item',
    name: '时间线项',
    category: ComponentCategories.DATA,
    icon: 'TimelineItem',
    isChildComponent: true,
    parentComponents: ['ea-timeline'],
    props: [
      {
        name: 'type',
        label: '类型',
        type: PropTypes.SELECT,
        default: 'info',
        options: [
          { label: '主要', value: 'primary' },
          { label: '成功', value: 'success' },
          { label: '警告', value: 'warning' },
          { label: '危险', value: 'danger' },
          { label: '信息', value: 'info' },
        ],
      },
      {
        name: 'timestamp',
        label: '时间戳',
        type: PropTypes.STRING,
        default: '',
      },
      {
        name: 'hide-timestamp',
        label: '隐藏时间戳',
        type: PropTypes.BOOLEAN,
        default: false,
      },
      {
        name: 'placement',
        label: '时间戳位置',
        type: PropTypes.SELECT,
        default: 'bottom',
        options: [
          { label: '上', value: 'top' },
          { label: '下', value: 'bottom' },
        ],
      },
      {
        name: 'size',
        label: '节点大小',
        type: PropTypes.SELECT,
        default: 'normal',
        options: [
          { label: '大', value: 'large' },
          { label: '普通', value: 'normal' },
        ],
      },
      {
        name: 'color',
        label: '自定义颜色',
        type: PropTypes.STRING,
        default: '',
      },
      {
        name: 'hollow',
        label: '空心节点',
        type: PropTypes.BOOLEAN,
        default: false,
      },
      {
        name: 'icon',
        label: '图标类名',
        type: PropTypes.STRING,
        default: '',
      },
      {
        name: 'center',
        label: '垂直居中',
        type: PropTypes.BOOLEAN,
        default: false,
      },
    ],
    events: [],
    slots: [
      { name: 'default', label: '内容插槽' },
      { name: 'dot', label: '圆点插槽' },
      { name: 'timestamp', label: '时间戳插槽' },
    ],
    styleConfig: {
      parts: [
        {
          name: 'container',
          label: '外层容器',
          styles: ['background-color'],
        },
        {
          name: 'left-wrapper',
          label: '左侧容器',
          styles: ['background-color'],
        },
        {
          name: 'dot',
          label: '默认节点容器',
          styles: ['background-color', 'border-color'],
        },
        {
          name: 'icon-dot',
          label: '节点图标',
          styles: ['color'],
        },
        {
          name: 'tail',
          label: '时间线线条',
          styles: ['background-color', 'border-color'],
        },
        {
          name: 'right-wrapper',
          label: '右侧容器',
          styles: ['background-color'],
        },
        {
          name: 'content',
          label: '内容容器',
          styles: ['color', 'font-size'],
        },
        {
          name: 'timestamp',
          label: '时间戳',
          styles: ['color', 'font-size'],
        },
      ],
    },
  },
  {
    type: 'ea-tree',
    name: '树形控件',
    category: ComponentCategories.DATA,
    icon: 'Tree',
    props: [
      {
        name: 'data',
        label: '数据',
        type: PropTypes.ARRAY,
        default: [],
      },
      {
        name: 'node-key',
        label: '节点键名',
        type: PropTypes.STRING,
        default: '',
      },
      {
        name: 'show-checkbox',
        label: '显示复选框',
        type: PropTypes.BOOLEAN,
        default: false,
      },
      {
        name: 'check-strictly',
        label: '严格模式（不关联父子节点）',
        type: PropTypes.BOOLEAN,
        default: false,
      },
      {
        name: 'expand-on-icon-click',
        label: '只在点击图标时展开/收起节点',
        type: PropTypes.BOOLEAN,
        default: false,
      },
      {
        name: 'dataProps',
        label: '数据字段配置',
        type: PropTypes.OBJECT,
        default: { children: 'children', label: 'label', disabled: 'disabled' },
      },
      {
        name: 'defaultExpandedKeys',
        label: '默认展开的节点键值数组',
        type: PropTypes.ARRAY,
        default: [],
      },
      {
        name: 'defaultCheckedKeys',
        label: '默认选中的节点键值数组',
        type: PropTypes.ARRAY,
        default: [],
      },
    ],
    events: [
      { name: 'ea-node-click', label: '节点点击' },
      { name: 'ea-node-contextmenu', label: '节点右键菜单' },
      { name: 'ea-node-select', label: '节点选中' },
      { name: 'ea-check-change', label: '复选框状态变化' },
      { name: 'ea-check', label: '复选框选中' },
      { name: 'ea-current-change', label: '当前选中节点变化' },
      { name: 'ea-node-expand', label: '节点展开' },
      { name: 'ea-node-collapse', label: '节点收起' },
    ],
    slots: [{ name: 'default', label: '默认插槽' }],
    styleConfig: {
      parts: [
        {
          name: 'container',
          label: '树容器',
          styles: ['background-color'],
        },
        {
          name: 'children-wrapper',
          label: '子节点容器',
          styles: ['background-color'],
        },
        {
          name: 'children',
          label: '子节点',
          styles: ['background-color'],
        },
        {
          name: 'label',
          label: '节点标签',
          styles: ['color', 'font-size'],
        },
      ],
    },
  },
]
