import { ComponentCategories, PropTypes } from '../types'
import type { ComponentMeta } from '../types'

// Feedback 反馈
export const feedbackComponents: ComponentMeta[] = [
  {
    type: 'ea-alert',
    name: '警告提示',
    category: ComponentCategories.FEEDBACK,
    icon: 'Alert',
    props: [
      {
        name: 'title',
        label: '标题',
        type: PropTypes.STRING,
        default: '',
      },
      {
        name: 'type',
        label: '类型',
        type: PropTypes.SELECT,
        default: 'info',
        options: [
          { label: '主要', value: 'primary' },
          { label: '成功', value: 'success' },
          { label: '警告', value: 'warning' },
          { label: '信息', value: 'info' },
          { label: '错误', value: 'error' },
        ],
      },
      {
        name: 'description',
        label: '辅助性文字',
        type: PropTypes.STRING,
        default: '',
      },
      {
        name: 'closable',
        label: '可关闭',
        type: PropTypes.BOOLEAN,
        default: false,
      },
      {
        name: 'center',
        label: '文字居中',
        type: PropTypes.BOOLEAN,
        default: false,
      },
      {
        name: 'close-text',
        label: '关闭按钮自定义文本',
        type: PropTypes.STRING,
        default: '',
      },
      {
        name: 'show-icon',
        label: '显示图标',
        type: PropTypes.BOOLEAN,
        default: false,
      },
      {
        name: 'effect',
        label: '主题效果',
        type: PropTypes.SELECT,
        default: 'light',
        options: [
          { label: '浅色', value: 'light' },
          { label: '深色', value: 'dark' },
        ],
      },
      {
        name: 'show-after',
        label: '延迟显示(ms)',
        type: PropTypes.NUMBER,
        default: 0,
      },
      {
        name: 'hide-after',
        label: '延迟关闭(ms)',
        type: PropTypes.NUMBER,
        default: 200,
      },
      {
        name: 'auto-close',
        label: '自动关闭延迟(ms)',
        type: PropTypes.NUMBER,
        default: 0,
      },
    ],
    events: [
      { name: 'open', label: '开启' },
      { name: 'close', label: '关闭' },
    ],
    slots: [
      { name: 'default', label: 'Alert 内容描述' },
      { name: 'title', label: '标题的内容' },
      { name: 'icon', label: '图标内容' },
    ],
    styleConfig: {
      parts: [
        {
          name: 'container',
          label: 'alert 外层容器',
          styles: ['background-color', 'border-color'],
        },
        {
          name: 'icon-wrap',
          label: 'alert 图标容器',
          styles: ['color'],
        },
        {
          name: 'icon',
          label: 'alert 图标',
          styles: ['color'],
        },
        {
          name: 'content-wrap',
          label: 'alert 内层容器',
          styles: ['color'],
        },
        {
          name: 'title',
          label: 'alert 标题容器',
          styles: ['color'],
        },
        {
          name: 'description',
          label: 'alert 描述容器',
          styles: ['color'],
        },
        {
          name: 'close-btn',
          label: 'alert 关闭按钮容器',
          styles: ['color'],
        },
        {
          name: 'close-icon',
          label: 'alert 关闭图标',
          styles: ['color'],
        },
      ],
    },
  },
  {
    type: 'ea-dialog',
    name: '对话框',
    category: ComponentCategories.FEEDBACK,
    icon: 'Dialog',
    props: [
      {
        name: 'visible',
        label: '是否可见',
        type: PropTypes.BOOLEAN,
        default: false,
      },
      {
        name: 'title',
        label: '标题',
        type: PropTypes.STRING,
        default: '',
      },
      {
        name: 'width',
        label: '宽度',
        type: PropTypes.STRING,
        default: '50%',
      },
      {
        name: 'center',
        label: '内容垂直居中',
        type: PropTypes.BOOLEAN,
        default: false,
      },
      {
        name: 'draggable',
        label: '可拖拽',
        type: PropTypes.BOOLEAN,
        default: false,
      },
      {
        name: 'fullscreen',
        label: '全屏显示',
        type: PropTypes.BOOLEAN,
        default: false,
      },
      {
        name: 'modal',
        label: '显示遮罩',
        type: PropTypes.BOOLEAN,
        default: true,
      },
      {
        name: 'append-to-body',
        label: '追加到body',
        type: PropTypes.BOOLEAN,
        default: false,
      },
      {
        name: 'show-close',
        label: '显示关闭图标',
        type: PropTypes.BOOLEAN,
        default: true,
      },
      {
        name: 'before-close',
        label: '启用关闭拦截',
        type: PropTypes.BOOLEAN,
        default: false,
      },
    ],
    events: [
      { name: 'open', label: '打开' },
      { name: 'opened', label: '打开完成' },
      { name: 'close', label: '关闭' },
      { name: 'closed', label: '关闭完成' },
    ],
    slots: [
      { name: 'default', label: '内容插槽' },
      { name: 'header', label: '头部插槽' },
      { name: 'footer', label: '底部插槽' },
    ],
    styleConfig: {
      parts: [
        {
          name: 'container',
          label: '对话框根容器',
          styles: ['background-color'],
        },
        {
          name: 'header',
          label: '头部容器',
          styles: ['background-color', 'border-color'],
        },
        {
          name: 'title',
          label: '标题文本',
          styles: ['color'],
        },
        {
          name: 'content',
          label: '主体内容',
          styles: ['background-color'],
        },
        {
          name: 'footer',
          label: '底部容器',
          styles: ['background-color', 'border-color'],
        },
      ],
    },
  },
  {
    type: 'ea-drawer',
    name: '抽屉',
    category: ComponentCategories.FEEDBACK,
    icon: 'Drawer',
    props: [
      {
        name: 'visible',
        label: '是否可见',
        type: PropTypes.BOOLEAN,
        default: false,
      },
      {
        name: 'title',
        label: '标题',
        type: PropTypes.STRING,
        default: '',
      },
      {
        name: 'size',
        label: '尺寸',
        type: PropTypes.UNIT,
        default: '30%',
      },
      {
        name: 'direction',
        label: '方向',
        type: PropTypes.SELECT,
        default: 'rtl',
        options: [
          { label: '左到右', value: 'ltr' },
          { label: '右到左', value: 'rtl' },
          { label: '上到下', value: 'ttb' },
          { label: '下到上', value: 'btt' },
        ],
      },
      {
        name: 'modal',
        label: '显示遮罩',
        type: PropTypes.BOOLEAN,
        default: true,
      },
      {
        name: 'close-on-click-modal',
        label: '点击遮罩关闭',
        type: PropTypes.BOOLEAN,
        default: true,
      },
      {
        name: 'close-on-press-escape',
        label: 'ESC关闭',
        type: PropTypes.BOOLEAN,
        default: true,
      },
      {
        name: 'before-close',
        label: '启用关闭拦截',
        type: PropTypes.BOOLEAN,
        default: false,
      },
      {
        name: 'show-close',
        label: '显示关闭图标',
        type: PropTypes.BOOLEAN,
        default: true,
      },
      {
        name: 'with-header',
        label: '显示头部',
        type: PropTypes.BOOLEAN,
        default: true,
      },
      {
        name: 'append-to-body',
        label: '追加到body',
        type: PropTypes.BOOLEAN,
        default: false,
      },
    ],
    events: [
      { name: 'open', label: '打开' },
      { name: 'opened', label: '打开完成' },
      { name: 'close', label: '关闭' },
      { name: 'closed', label: '关闭完成' },
      { name: 'before-close', label: '关闭前' },
    ],
    slots: [
      { name: 'default', label: '内容插槽' },
      { name: 'title', label: '标题插槽' },
      { name: 'footer', label: '底部插槽' },
    ],
    styleConfig: {
      parts: [
        {
          name: 'container',
          label: '外层容器',
          styles: ['background-color'],
        },
        {
          name: 'header',
          label: '头部容器',
          styles: ['background-color', 'border-color'],
        },
        {
          name: 'title',
          label: '标题容器',
          styles: ['color'],
        },
        {
          name: 'content',
          label: '内容区域',
          styles: ['background-color'],
        },
        {
          name: 'footer',
          label: '底部区域',
          styles: ['background-color', 'border-color'],
        },
      ],
    },
  },
  {
    type: 'ea-message',
    name: '消息提示',
    category: ComponentCategories.FEEDBACK,
    icon: 'Message',
    isService: true,
    props: [
      {
        name: 'message',
        label: '消息文字',
        type: PropTypes.STRING,
        default: '',
      },
      {
        name: 'type',
        label: '类型',
        type: PropTypes.SELECT,
        default: 'info',
        options: [
          { label: '主要', value: 'primary' },
          { label: '成功', value: 'success' },
          { label: '警告', value: 'warning' },
          { label: '信息', value: 'info' },
          { label: '错误', value: 'error' },
        ],
      },
      {
        name: 'duration',
        label: '显示时长(ms)',
        type: PropTypes.NUMBER,
        default: 3000,
      },
      {
        name: 'showClose',
        label: '显示关闭按钮',
        type: PropTypes.BOOLEAN,
        default: false,
      },
      {
        name: 'dangerouslyUseHTMLString',
        label: 'HTML渲染',
        type: PropTypes.BOOLEAN,
        default: false,
      },
      {
        name: 'offset',
        label: '偏移距离',
        type: PropTypes.NUMBER,
        default: 16,
      },
      {
        name: 'placement',
        label: '出现位置',
        type: PropTypes.SELECT,
        default: 'top',
        options: [
          { label: '顶部', value: 'top' },
          { label: '左上', value: 'top-left' },
          { label: '右上', value: 'top-right' },
          { label: '底部', value: 'bottom' },
          { label: '左下', value: 'bottom-left' },
          { label: '右下', value: 'bottom-right' },
        ],
      },
      {
        name: 'appendTo',
        label: '挂载目标',
        type: PropTypes.STRING,
        default: 'body',
      },
    ],
    events: [
      { name: 'show', label: '显示' },
      { name: 'shown', label: '显示完成' },
      { name: 'hide', label: '隐藏' },
      { name: 'hidden', label: '隐藏完成' },
      { name: 'close', label: '关闭' },
    ],
    slots: [],
    styleConfig: {
      parts: [
        {
          name: 'container',
          label: '消息容器',
          styles: ['background-color', 'border-color', 'border-radius', 'box-shadow'],
        },
        {
          name: 'icon',
          label: '类型图标',
          styles: ['color'],
        },
        {
          name: 'content-wrap',
          label: '内容区域',
          styles: ['color'],
        },
        {
          name: 'close-icon',
          label: '关闭按钮',
          styles: ['color'],
        },
      ],
    },
    methods: [
      {
        name: 'close',
        label: '关闭消息',
        description: '关闭当前的 Message',
      },
    ],
  },
  {
    type: 'ea-message-box',
    name: '消息弹出框',
    category: ComponentCategories.FEEDBACK,
    icon: 'MessageBox',
    isService: true,
    props: [
      {
        name: 'title',
        label: '标题',
        type: PropTypes.STRING,
        default: '',
      },
      {
        name: 'message',
        label: '正文内容',
        type: PropTypes.STRING,
        default: '',
      },
      {
        name: 'type',
        label: '类型',
        type: PropTypes.SELECT,
        default: '',
        options: [
          { label: '主要', value: 'primary' },
          { label: '成功', value: 'success' },
          { label: '信息', value: 'info' },
          { label: '警告', value: 'warning' },
          { label: '错误', value: 'error' },
        ],
      },
      {
        name: 'dangerouslyUseHTMLString',
        label: 'HTML渲染',
        type: PropTypes.BOOLEAN,
        default: false,
      },
      {
        name: 'showClose',
        label: '显示关闭按钮',
        type: PropTypes.BOOLEAN,
        default: true,
      },
      {
        name: 'distinguishCancelAndClose',
        label: '区分取消和关闭',
        type: PropTypes.BOOLEAN,
        default: false,
      },
      {
        name: 'showCancelButton',
        label: '显示取消按钮',
        type: PropTypes.BOOLEAN,
        default: false,
      },
      {
        name: 'showConfirmButton',
        label: '显示确认按钮',
        type: PropTypes.BOOLEAN,
        default: true,
      },
      {
        name: 'confirmButtonText',
        label: '确认按钮文本',
        type: PropTypes.STRING,
        default: '确认',
      },
      {
        name: 'cancelButtonText',
        label: '取消按钮文本',
        type: PropTypes.STRING,
        default: '取消',
      },
      {
        name: 'closeOnClickModal',
        label: '点击遮罩关闭',
        type: PropTypes.BOOLEAN,
        default: true,
      },
      {
        name: 'closeOnPressEscape',
        label: 'ESC关闭',
        type: PropTypes.BOOLEAN,
        default: true,
      },
      {
        name: 'showInput',
        label: '显示输入框',
        type: PropTypes.BOOLEAN,
        default: false,
      },
      {
        name: 'center',
        label: '内容垂直居中',
        type: PropTypes.BOOLEAN,
        default: false,
      },
      {
        name: 'draggable',
        label: '可拖拽',
        type: PropTypes.BOOLEAN,
        default: false,
      },
      {
        name: 'roundButton',
        label: '圆形按钮',
        type: PropTypes.BOOLEAN,
        default: false,
      },
      {
        name: 'buttonSize',
        label: '按钮尺寸',
        type: PropTypes.SELECT,
        default: 'large',
        options: [
          { label: '小', value: 'small' },
          { label: '中', value: 'default' },
          { label: '大', value: 'large' },
        ],
      },
    ],
    events: [
      { name: 'confirm', label: '确认' },
      { name: 'cancel', label: '取消' },
      { name: 'message-close', label: '关闭' },
    ],
    slots: [],
  },
  {
    type: 'ea-notification',
    name: '通知',
    isService: true,
    category: ComponentCategories.FEEDBACK,
    icon: 'Notification',
    props: [
      {
        name: 'title',
        label: '标题',
        type: PropTypes.STRING,
        default: '',
      },
      {
        name: 'message',
        label: '正文内容',
        type: PropTypes.STRING,
        default: '',
      },
      {
        name: 'type',
        label: '类型',
        type: PropTypes.SELECT,
        default: 'info',
        options: [
          { label: '成功', value: 'success' },
          { label: '警告', value: 'warning' },
          { label: '信息', value: 'info' },
          { label: '错误', value: 'error' },
          { label: '主要', value: 'primary' },
        ],
      },
      {
        name: 'icon',
        label: '自定义图标',
        type: PropTypes.STRING,
        default: '',
      },
      {
        name: 'duration',
        label: '显示时长(ms)',
        type: PropTypes.NUMBER,
        default: 3000,
      },
      {
        name: 'placement',
        label: '出现位置',
        type: PropTypes.SELECT,
        default: 'top-right',
        options: [
          { label: '右上', value: 'top-right' },
          { label: '左上', value: 'top-left' },
          { label: '右下', value: 'bottom-right' },
          { label: '左下', value: 'bottom-left' },
        ],
      },
      {
        name: 'showClose',
        label: '显示关闭按钮',
        type: PropTypes.BOOLEAN,
        default: true,
      },
      {
        name: 'closeIcon',
        label: '关闭按钮图标',
        type: PropTypes.STRING,
        default: 'icon-cancel',
      },
      {
        name: 'dangerouslyUseHTMLString',
        label: 'HTML渲染',
        type: PropTypes.BOOLEAN,
        default: false,
      },
      {
        name: 'zIndex',
        label: 'z-index',
        type: PropTypes.NUMBER,
        default: 0,
      },
      {
        name: 'appendTo',
        label: '挂载容器',
        type: PropTypes.STRING,
        default: 'body',
      },
    ],
    events: [
      { name: 'show', label: '显示' },
      { name: 'shown', label: '显示完成' },
      { name: 'hide', label: '隐藏' },
      { name: 'hidden', label: '隐藏完成' },
      { name: 'close', label: '关闭' },
    ],
    slots: [],
  },
  {
    type: 'ea-popconfirm',
    name: '气泡确认框',
    category: ComponentCategories.FEEDBACK,
    icon: 'Popconfirm',
    props: [
      {
        name: 'title',
        label: '标题',
        type: PropTypes.STRING,
        default: '',
      },
      {
        name: 'width',
        label: '宽度',
        type: PropTypes.NUMBER,
        default: 150,
      },
      {
        name: 'confirm-button-text',
        label: '确认按钮文本',
        type: PropTypes.STRING,
        default: '确认',
      },
      {
        name: 'cancel-button-text',
        label: '取消按钮文本',
        type: PropTypes.STRING,
        default: '取消',
      },
      {
        name: 'confirm-button-type',
        label: '确认按钮类型',
        type: PropTypes.SELECT,
        default: 'primary',
        options: [
          { label: '主要', value: 'primary' },
          { label: '成功', value: 'success' },
          { label: '警告', value: 'warning' },
          { label: '危险', value: 'danger' },
          { label: '信息', value: 'info' },
          { label: '默认', value: 'default' },
        ],
      },
      {
        name: 'cancel-button-type',
        label: '取消按钮类型',
        type: PropTypes.SELECT,
        default: 'default',
        options: [
          { label: '主要', value: 'primary' },
          { label: '成功', value: 'success' },
          { label: '警告', value: 'warning' },
          { label: '危险', value: 'danger' },
          { label: '信息', value: 'info' },
          { label: '默认', value: 'default' },
        ],
      },
      {
        name: 'icon',
        label: '图标',
        type: PropTypes.STRING,
        default: 'icon-question',
      },
      {
        name: 'icon-color',
        label: '确认框图标的颜色',
        type: PropTypes.COLOR,
        default: '#f90',
      },
      {
        name: 'placement',
        label: '气泡的出现位置',
        type: PropTypes.SELECT,
        default: 'top',
        options: [
          { label: '顶部', value: 'top' },
          { label: '顶部起始', value: 'top-start' },
          { label: '顶部结束', value: 'top-end' },
          { label: '底部', value: 'bottom' },
          { label: '底部起始', value: 'bottom-start' },
          { label: '底部结束', value: 'bottom-end' },
          { label: '左侧', value: 'left' },
          { label: '左侧起始', value: 'left-start' },
          { label: '左侧结束', value: 'left-end' },
          { label: '右侧', value: 'right' },
          { label: '右侧起始', value: 'right-start' },
          { label: '右侧结束', value: 'right-end' },
        ],
      },
      {
        name: 'show-arrow',
        label: '是否显示箭头',
        type: PropTypes.BOOLEAN,
        default: false,
      },
      {
        name: 'visible',
        label: '控制 Popover 显隐的属性',
        type: PropTypes.BOOLEAN,
        default: false,
      },
      {
        name: 'offset',
        label: '气泡出现的位置偏移量',
        type: PropTypes.STRING,
        default: '0 0',
      },
      {
        name: 'flip',
        label: '是否在超过原 placement 视口时进行翻转',
        type: PropTypes.BOOLEAN,
        default: true,
      },
    ],
    events: [
      { name: 'confirm', label: '点击确认按钮时触发' },
      { name: 'cancel', label: '点击取消按钮时触发' },
    ],
    defaultSlot: 'reference',
    slots: [
      { name: 'reference', label: '触发 Popover 显示的 HTML 元素插槽' },
      { name: 'actions', label: '页脚的内容' },
    ],
    styleConfig: {
      parts: [
        {
          name: 'container',
          label: 'Popconfirm 外层容器',
          styles: ['background-color'],
        },
        {
          name: 'reference',
          label: '触发 Popconfirm 显示的 HTML 元素的父容器',
          styles: [],
        },
        {
          name: 'title',
          label: 'Popconfirm 标题容器',
          styles: [],
        },
        {
          name: 'icon',
          label: 'Popconfirm 的图标',
          styles: [],
        },
        {
          name: 'title-content',
          label: 'Popconfirm 内容容器',
          styles: ['color'],
        },
        {
          name: 'footer',
          label: 'Popconfirm 底部容器',
          styles: ['background-color'],
        },
        {
          name: 'cancel-button',
          label: 'Popconfirm 取消按钮',
          styles: [],
        },
        {
          name: 'confirm-button',
          label: 'Popconfirm 确认按钮',
          styles: [],
        },
      ],
    },
  },
  {
    type: 'ea-popover',
    name: '弹出框',
    category: ComponentCategories.FEEDBACK,
    icon: 'Popover',
    defaultSlot: 'reference',
    props: [
      {
        name: 'trigger',
        label: '触发方式',
        type: PropTypes.SELECT,
        default: 'hover',
        options: [
          { label: '悬停', value: 'hover' },
          { label: '点击', value: 'click' },
          { label: '聚焦', value: 'focus' },
          { label: '右键', value: 'contextmenu' },
          { label: '自定义', value: 'customized' },
        ],
      },
      {
        name: 'title',
        label: '标题',
        type: PropTypes.STRING,
        default: '',
      },
      {
        name: 'content',
        label: '内容',
        type: PropTypes.STRING,
        default: '',
      },
      {
        name: 'width',
        label: '宽度',
        type: PropTypes.NUMBER,
        default: 150,
      },
      {
        name: 'placement',
        label: '气泡的出现位置',
        type: PropTypes.SELECT,
        default: 'top',
        options: [
          { label: '顶部', value: 'top' },
          { label: '顶部起始', value: 'top-start' },
          { label: '顶部结束', value: 'top-end' },
          { label: '底部', value: 'bottom' },
          { label: '底部起始', value: 'bottom-start' },
          { label: '底部结束', value: 'bottom-end' },
          { label: '左侧', value: 'left' },
          { label: '左侧起始', value: 'left-start' },
          { label: '左侧结束', value: 'left-end' },
          { label: '右侧', value: 'right' },
          { label: '右侧起始', value: 'right-start' },
          { label: '右侧结束', value: 'right-end' },
        ],
      },
      {
        name: 'show-arrow',
        label: '是否显示箭头',
        type: PropTypes.BOOLEAN,
        default: false,
      },
      {
        name: 'visible',
        label: '控制 Popover 显隐的属性',
        type: PropTypes.BOOLEAN,
        default: false,
      },
      {
        name: 'offset',
        label: '气泡出现的位置偏移量',
        type: PropTypes.STRING,
        default: '0 0',
      },
      {
        name: 'flip',
        label: '是否在超过原 placement 视口时，进行翻转',
        type: PropTypes.BOOLEAN,
        default: true,
      },
    ],
    events: [
      { name: 'show', label: '开启 Popover 时触发的事件' },
      { name: 'shown', label: '开启 Popover 的动画结束时触发' },
      { name: 'hide', label: '关闭 Popover 时触发的事件' },
      { name: 'hidden', label: '关闭 Popover 的动画结束时触发' },
    ],
    slots: [
      { name: 'default', label: 'Popover 内容插槽' },
      { name: 'reference', label: '触发 Popover 显示的 HTML 元素插槽' },
    ],
    styleConfig: {
      parts: [
        {
          name: 'container',
          label: 'Popover 外层容器',
          styles: ['background-color'],
        },
        {
          name: 'reference',
          label: '触发 Popover 显示的 HTML 元素的父容器',
          styles: [],
        },
        {
          name: 'original',
          label: 'Popover 内容容器',
          styles: ['background-color'],
        },
        {
          name: 'title',
          label: 'Popover 标题容器',
          styles: ['color'],
        },
        {
          name: 'content',
          label: 'Popover 内容容器',
          styles: ['color'],
        },
      ],
    },
  },
  {
    type: 'ea-tooltip',
    name: '文字提示',
    category: ComponentCategories.FEEDBACK,
    icon: 'Tooltip',
    defaultSlot: 'reference',
    props: [
      {
        name: 'effect',
        label: '显示效果',
        type: PropTypes.SELECT,
        default: 'dark',
        options: [
          { label: '深色', value: 'dark' },
          { label: '浅色', value: 'light' },
          { label: '自定义', value: 'customized' },
        ],
      },
      {
        name: 'trigger',
        label: '触发方式',
        type: PropTypes.SELECT,
        default: 'hover',
        options: [
          { label: '悬停', value: 'hover' },
          { label: '点击', value: 'click' },
          { label: '聚焦', value: 'focus' },
          { label: '右键', value: 'contextmenu' },
          { label: '自定义', value: 'customized' },
        ],
      },
      {
        name: 'content',
        label: '内容',
        type: PropTypes.STRING,
        default: '',
      },
      {
        name: 'width',
        label: '宽度(px)',
        type: PropTypes.NUMBER,
        default: 150,
      },
      {
        name: 'placement',
        label: '气泡的出现位置',
        type: PropTypes.SELECT,
        default: 'top',
        options: [
          { label: '顶部', value: 'top' },
          { label: '顶部起始', value: 'top-start' },
          { label: '顶部结束', value: 'top-end' },
          { label: '底部', value: 'bottom' },
          { label: '底部起始', value: 'bottom-start' },
          { label: '底部结束', value: 'bottom-end' },
          { label: '左侧', value: 'left' },
          { label: '左侧起始', value: 'left-start' },
          { label: '左侧结束', value: 'left-end' },
          { label: '右侧', value: 'right' },
          { label: '右侧起始', value: 'right-start' },
          { label: '右侧结束', value: 'right-end' },
        ],
      },
      {
        name: 'show-arrow',
        label: '是否显示箭头',
        type: PropTypes.BOOLEAN,
        default: false,
      },
      {
        name: 'offset',
        label: '气泡出现的位置偏移量',
        type: PropTypes.STRING,
        default: '0 0',
      },
    ],
    events: [
      { name: 'show', label: '开启 Tooltip 时触发的事件' },
      { name: 'shown', label: '开启 Tooltip 的动画结束时触发' },
      { name: 'hide', label: '关闭 Tooltip 时触发的事件' },
      { name: 'hidden', label: '关闭 Tooltip 的动画结束时触发' },
    ],
    slots: [
      { name: 'default', label: 'Tooltip 内容插槽' },
      { name: 'reference', label: '触发 Tooltip 显示的 HTML 元素插槽' },
    ],
    styleConfig: {
      parts: [
        {
          name: 'container',
          label: 'Tooltip 外层容器',
          styles: ['background-color'],
        },
        {
          name: 'reference',
          label: '触发 Tooltip 显示的 HTML 元素的父容器',
          styles: [],
        },
        {
          name: 'original',
          label: 'Tooltip 内容容器',
          styles: ['background-color', 'color'],
        },
        {
          name: 'content',
          label: 'Tooltip 内容容器',
          styles: ['color'],
        },
      ],
    },
  },
]
