import type { ComponentSchema } from '../types/index.js';
export declare function findComponentById(components: ComponentSchema[], id: string | null): ComponentSchema | null;
export declare function findParentComponent(components: ComponentSchema[], targetId: string, parent?: ComponentSchema | null): ComponentSchema | null;
export declare function traverseComponents(components: ComponentSchema[], callback: (component: ComponentSchema, parent: ComponentSchema | null, index: number) => boolean | void): void;
export declare function flattenComponents(components: ComponentSchema[]): ComponentSchema[];
export declare function getComponentTreeDepth(components: ComponentSchema[]): number;
export declare function findComponentPath(components: ComponentSchema[], targetId: string): string[] | null;
export declare function insertComponent(components: ComponentSchema[], component: ComponentSchema, parentId: string | null, index?: number): ComponentSchema[];
export declare function removeComponent(components: ComponentSchema[], targetId: string): ComponentSchema[];
export declare function moveComponent(components: ComponentSchema[], sourceId: string, targetParentId: string | null, targetIndex?: number): ComponentSchema[];
export declare function findComponentByAlias(components: ComponentSchema[], alias: string): ComponentSchema | null;
