const generateId = () =>
  `comp_${Date.now()}_${Math.random().toString(36).substring(2, 10)}`;

export const TEMPLATES: Record<string, { name: string; schema: any }> = {
  dashboard: {
    name: '数据看板',
    schema: {
      meta: {
        title: '数据看板',
        description: '',
      },
      layout: {
        type: 'absolute',
        config: {},
      },
      version: '1.0',
      components: [
        {
          id: generateId(),
          type: 'ea-container',
          props: { direction: 'vertical' },
          slots: {},
          style: {
            padding: '24px',
            minHeight: '100vh',
            backgroundColor: '#f0f2f5',
          },
          events: [],
          children: [
            {
              id: generateId(),
              type: 'ea-row',
              props: { gutter: 16, align: 'middle' },
              slots: {},
              style: { marginBottom: '20px' },
              events: [],
              children: [
                {
                  id: generateId(),
                  type: 'ea-col',
                  props: { span: 16 },
                  slots: {},
                  style: {},
                  events: [],
                  children: [
                    {
                      id: generateId(),
                      type: 'ea-text',
                      props: { children: '工作台', size: 'large' },
                      slots: {},
                      style: {
                        fontWeight: '600',
                        color: '#1d2129',
                        display: 'block',
                      },
                      events: [],
                      children: [],
                    },
                    {
                      id: generateId(),
                      type: 'ea-text',
                      props: {
                        children: '欢迎回来，管理员，祝您今天工作愉快！',
                        size: 'medium',
                        type: 'info',
                      },
                      slots: {},
                      style: { marginTop: '6px', display: 'block' },
                      events: [],
                      children: [],
                    },
                  ],
                },
                {
                  id: generateId(),
                  type: 'ea-col',
                  props: { span: 8 },
                  slots: {},
                  style: { textAlign: 'right' },
                  events: [],
                  children: [
                    {
                      id: generateId(),
                      type: 'ea-text',
                      props: {
                        children: '2024年01月15日 星期一',
                        size: 'small',
                        type: 'info',
                      },
                      slots: {},
                      style: {},
                      events: [],
                      children: [],
                    },
                  ],
                },
              ],
            },
            {
              id: generateId(),
              type: 'ea-row',
              props: { gutter: 16 },
              slots: {},
              style: { marginBottom: '20px' },
              events: [],
              children: [
                {
                  id: generateId(),
                  type: 'ea-col',
                  props: { span: 6 },
                  slots: {},
                  style: {},
                  events: [],
                  children: [
                    {
                      id: generateId(),
                      type: 'ea-card',
                      props: { shadow: 'hover' },
                      slots: {},
                      style: {
                        borderRadius: '8px',
                        borderLeft: '4px solid #1890ff',
                        padding: '20px',
                      },
                      events: [],
                      children: [
                        {
                          id: generateId(),
                          type: 'ea-row',
                          props: { align: 'middle', justify: 'space-between' },
                          slots: {},
                          style: { marginBottom: '12px' },
                          events: [],
                          children: [
                            {
                              id: generateId(),
                              type: 'ea-col',
                              props: { span: 12 },
                              slots: {},
                              style: {},
                              events: [],
                              children: [
                                {
                                  id: generateId(),
                                  type: 'ea-text',
                                  props: {
                                    children: '总销售额',
                                    size: 'medium',
                                    type: 'info',
                                  },
                                  slots: {},
                                  style: {},
                                  events: [],
                                  children: [],
                                },
                              ],
                            },
                            {
                              id: generateId(),
                              type: 'ea-col',
                              props: { span: 12 },
                              slots: {},
                              style: { textAlign: 'right' },
                              events: [],
                              children: [
                                {
                                  id: generateId(),
                                  type: 'ea-icon',
                                  props: {
                                    name: 'chart-line',
                                    size: '24',
                                    color: '#1890ff',
                                  },
                                  slots: {},
                                  style: {},
                                  events: [],
                                  children: [],
                                },
                              ],
                            },
                          ],
                        },
                        {
                          id: generateId(),
                          type: 'ea-statistic',
                          props: { value: '128000' },
                          slots: {},
                          style: {},
                          events: [],
                          children: [
                            {
                              id: generateId(),
                              type: 'ea-text',
                              props: {
                                slot: 'suffix',
                                size: 'small',
                                children: ' 元',
                              },
                              slots: {},
                              style: {},
                              events: [],
                              children: [],
                            },
                          ],
                        },
                        {
                          id: generateId(),
                          type: 'ea-text',
                          props: {
                            children: '↑ 12.5% 较上周',
                            size: 'small',
                            type: 'success',
                          },
                          slots: {},
                          style: { marginTop: '8px', display: 'block' },
                          events: [],
                          children: [],
                        },
                      ],
                    },
                  ],
                },
                {
                  id: generateId(),
                  type: 'ea-col',
                  props: { span: 6 },
                  slots: {},
                  style: {},
                  events: [],
                  children: [
                    {
                      id: generateId(),
                      type: 'ea-card',
                      props: { shadow: 'hover' },
                      slots: {},
                      style: {
                        borderRadius: '8px',
                        borderLeft: '4px solid #52c41a',
                        padding: '20px',
                      },
                      events: [],
                      children: [
                        {
                          id: generateId(),
                          type: 'ea-row',
                          props: { align: 'middle', justify: 'space-between' },
                          slots: {},
                          style: { marginBottom: '12px' },
                          events: [],
                          children: [
                            {
                              id: generateId(),
                              type: 'ea-col',
                              props: { span: 12 },
                              slots: {},
                              style: {},
                              events: [],
                              children: [
                                {
                                  id: generateId(),
                                  type: 'ea-text',
                                  props: {
                                    children: '订单总数',
                                    size: 'medium',
                                    type: 'info',
                                  },
                                  slots: {},
                                  style: {},
                                  events: [],
                                  children: [],
                                },
                              ],
                            },
                            {
                              id: generateId(),
                              type: 'ea-col',
                              props: { span: 12 },
                              slots: {},
                              style: { textAlign: 'right' },
                              events: [],
                              children: [
                                {
                                  id: generateId(),
                                  type: 'ea-icon',
                                  props: {
                                    name: 'cart-shopping',
                                    size: '24',
                                    color: '#52c41a',
                                  },
                                  slots: {},
                                  style: {},
                                  events: [],
                                  children: [],
                                },
                              ],
                            },
                          ],
                        },
                        {
                          id: generateId(),
                          type: 'ea-statistic',
                          props: { value: '3560' },
                          slots: {},
                          style: {},
                          events: [],
                          children: [
                            {
                              id: generateId(),
                              type: 'ea-text',
                              props: {
                                slot: 'suffix',
                                size: 'small',
                                children: ' 单',
                              },
                              slots: {},
                              style: {},
                              events: [],
                              children: [],
                            },
                          ],
                        },
                        {
                          id: generateId(),
                          type: 'ea-text',
                          props: {
                            children: '↑ 8.2% 较上周',
                            size: 'small',
                            type: 'success',
                          },
                          slots: {},
                          style: { marginTop: '8px', display: 'block' },
                          events: [],
                          children: [],
                        },
                      ],
                    },
                  ],
                },
                {
                  id: generateId(),
                  type: 'ea-col',
                  props: { span: 6 },
                  slots: {},
                  style: {},
                  events: [],
                  children: [
                    {
                      id: generateId(),
                      type: 'ea-card',
                      props: { shadow: 'hover' },
                      slots: {},
                      style: {
                        borderRadius: '8px',
                        borderLeft: '4px solid #faad14',
                        padding: '20px',
                      },
                      events: [],
                      children: [
                        {
                          id: generateId(),
                          type: 'ea-row',
                          props: { align: 'middle', justify: 'space-between' },
                          slots: {},
                          style: { marginBottom: '12px' },
                          events: [],
                          children: [
                            {
                              id: generateId(),
                              type: 'ea-col',
                              props: { span: 12 },
                              slots: {},
                              style: {},
                              events: [],
                              children: [
                                {
                                  id: generateId(),
                                  type: 'ea-text',
                                  props: {
                                    children: '访客数量',
                                    size: 'medium',
                                    type: 'info',
                                  },
                                  slots: {},
                                  style: {},
                                  events: [],
                                  children: [],
                                },
                              ],
                            },
                            {
                              id: generateId(),
                              type: 'ea-col',
                              props: { span: 12 },
                              slots: {},
                              style: { textAlign: 'right' },
                              events: [],
                              children: [
                                {
                                  id: generateId(),
                                  type: 'ea-icon',
                                  props: {
                                    name: 'users',
                                    size: '24',
                                    color: '#faad14',
                                  },
                                  slots: {},
                                  style: {},
                                  events: [],
                                  children: [],
                                },
                              ],
                            },
                          ],
                        },
                        {
                          id: generateId(),
                          type: 'ea-statistic',
                          props: { value: '8920' },
                          slots: {},
                          style: {},
                          events: [],
                          children: [
                            {
                              id: generateId(),
                              type: 'ea-text',
                              props: {
                                slot: 'suffix',
                                size: 'small',
                                children: ' 人',
                              },
                              slots: {},
                              style: {},
                              events: [],
                              children: [],
                            },
                          ],
                        },
                        {
                          id: generateId(),
                          type: 'ea-text',
                          props: {
                            children: '↓ 3.1% 较上周',
                            size: 'small',
                            type: 'danger',
                          },
                          slots: {},
                          style: { marginTop: '8px', display: 'block' },
                          events: [],
                          children: [],
                        },
                      ],
                    },
                  ],
                },
                {
                  id: generateId(),
                  type: 'ea-col',
                  props: { span: 6 },
                  slots: {},
                  style: {},
                  events: [],
                  children: [
                    {
                      id: generateId(),
                      type: 'ea-card',
                      props: { shadow: 'hover' },
                      slots: {},
                      style: {
                        borderRadius: '8px',
                        borderLeft: '4px solid #722ed1',
                        padding: '20px',
                      },
                      events: [],
                      children: [
                        {
                          id: generateId(),
                          type: 'ea-row',
                          props: { align: 'middle', justify: 'space-between' },
                          slots: {},
                          style: { marginBottom: '12px' },
                          events: [],
                          children: [
                            {
                              id: generateId(),
                              type: 'ea-col',
                              props: { span: 12 },
                              slots: {},
                              style: {},
                              events: [],
                              children: [
                                {
                                  id: generateId(),
                                  type: 'ea-text',
                                  props: {
                                    children: '转化率',
                                    size: 'medium',
                                    type: 'info',
                                  },
                                  slots: {},
                                  style: {},
                                  events: [],
                                  children: [],
                                },
                              ],
                            },
                            {
                              id: generateId(),
                              type: 'ea-col',
                              props: { span: 12 },
                              slots: {},
                              style: { textAlign: 'right' },
                              events: [],
                              children: [
                                {
                                  id: generateId(),
                                  type: 'ea-icon',
                                  props: {
                                    name: 'percentage',
                                    size: '24',
                                    color: '#722ed1',
                                  },
                                  slots: {},
                                  style: {},
                                  events: [],
                                  children: [],
                                },
                              ],
                            },
                          ],
                        },
                        {
                          id: generateId(),
                          type: 'ea-statistic',
                          props: { value: '72.8' },
                          slots: {},
                          style: {},
                          events: [],
                          children: [
                            {
                              id: generateId(),
                              type: 'ea-text',
                              props: {
                                slot: 'suffix',
                                size: 'small',
                                children: ' %',
                              },
                              slots: {},
                              style: {},
                              events: [],
                              children: [],
                            },
                          ],
                        },
                        {
                          id: generateId(),
                          type: 'ea-text',
                          props: {
                            children: '↑ 2.4% 较上周',
                            size: 'small',
                            type: 'success',
                          },
                          slots: {},
                          style: { marginTop: '8px', display: 'block' },
                          events: [],
                          children: [],
                        },
                      ],
                    },
                  ],
                },
              ],
            },
            {
              id: generateId(),
              type: 'ea-row',
              props: { gutter: 16 },
              slots: {},
              style: { marginBottom: '20px' },
              events: [],
              children: [
                {
                  id: generateId(),
                  type: 'ea-col',
                  props: { span: 16 },
                  slots: {},
                  style: {},
                  events: [],
                  children: [
                    {
                      id: generateId(),
                      type: 'ea-card',
                      props: { shadow: 'always' },
                      slots: {},
                      style: { borderRadius: '8px' },
                      events: [],
                      children: [
                        {
                          id: generateId(),
                          type: 'ea-text',
                          props: {
                            slot: 'header',
                            children: '最近订单',
                            size: 'medium',
                          },
                          slots: {},
                          style: {
                            fontWeight: '600',
                            padding: '16px 20px',
                            borderBottom: '1px solid #f0f0f0',
                          },
                          events: [],
                          children: [],
                        },
                        {
                          id: generateId(),
                          type: 'ea-table',
                          props: { stripe: true },
                          slots: {},
                          style: { width: '100%' },
                          events: [],
                          children: [
                            {
                              id: generateId(),
                              type: 'ea-table-column',
                              props: {
                                label: '订单号',
                                prop: 'orderNo',
                                width: '180px',
                              },
                              slots: {},
                              style: {},
                              events: [],
                              children: [],
                            },
                            {
                              id: generateId(),
                              type: 'ea-table-column',
                              props: {
                                label: '客户名称',
                                prop: 'customer',
                                width: '120px',
                              },
                              slots: {},
                              style: {},
                              events: [],
                              children: [],
                            },
                            {
                              id: generateId(),
                              type: 'ea-table-column',
                              props: {
                                label: '金额',
                                prop: 'amount',
                                width: '120px',
                                align: 'right',
                              },
                              slots: {},
                              style: {},
                              events: [],
                              children: [],
                            },
                            {
                              id: generateId(),
                              type: 'ea-table-column',
                              props: {
                                label: '状态',
                                prop: 'status',
                                width: '100px',
                                align: 'center',
                              },
                              slots: {},
                              style: {},
                              events: [],
                              children: [],
                            },
                            {
                              id: generateId(),
                              type: 'ea-table-column',
                              props: {
                                label: '下单时间',
                                prop: 'createdAt',
                                width: '160px',
                                align: 'center',
                              },
                              slots: {},
                              style: {},
                              events: [],
                              children: [],
                            },
                          ],
                          alias: 'orderTable',
                        },
                      ],
                    },
                  ],
                },
                {
                  id: generateId(),
                  type: 'ea-col',
                  props: { span: 8 },
                  slots: {},
                  style: {},
                  events: [],
                  children: [
                    {
                      id: generateId(),
                      type: 'ea-card',
                      props: { shadow: 'always' },
                      slots: {},
                      style: { borderRadius: '8px', marginBottom: '16px' },
                      events: [],
                      children: [
                        {
                          id: generateId(),
                          type: 'ea-text',
                          props: {
                            slot: 'header',
                            children: '日历',
                            size: 'medium',
                          },
                          slots: {},
                          style: {
                            fontWeight: '600',
                            padding: '16px 20px',
                            borderBottom: '1px solid #f0f0f0',
                          },
                          events: [],
                          children: [],
                        },
                        {
                          id: generateId(),
                          type: 'ea-calendar',
                          props: {},
                          slots: {},
                          style: {},
                          events: [],
                          children: [],
                        },
                      ],
                    },
                    {
                      id: generateId(),
                      type: 'ea-card',
                      props: { shadow: 'always' },
                      slots: {},
                      style: { borderRadius: '8px' },
                      events: [],
                      children: [
                        {
                          id: generateId(),
                          type: 'ea-text',
                          props: {
                            slot: 'header',
                            children: '待办事项',
                            size: 'medium',
                          },
                          slots: {},
                          style: {
                            fontWeight: '600',
                            padding: '16px 20px',
                            borderBottom: '1px solid #f0f0f0',
                          },
                          events: [],
                          children: [],
                        },
                        {
                          id: generateId(),
                          type: 'ea-collapse',
                          props: { accordion: true },
                          slots: {},
                          style: {},
                          events: [],
                          children: [
                            {
                              id: generateId(),
                              type: 'ea-collapse-item',
                              props: { title: '今日待办 (3)', name: 'today' },
                              slots: {},
                              style: {},
                              events: [],
                              children: [
                                {
                                  id: generateId(),
                                  type: 'ea-text',
                                  props: { children: '审批新用户注册申请' },
                                  slots: {},
                                  style: {
                                    display: 'block',
                                    padding: '6px 0',
                                    fontSize: '14px',
                                  },
                                  events: [],
                                  children: [],
                                },
                                {
                                  id: generateId(),
                                  type: 'ea-text',
                                  props: { children: '核对本月财务报表' },
                                  slots: {},
                                  style: {
                                    display: 'block',
                                    padding: '6px 0',
                                    fontSize: '14px',
                                  },
                                  events: [],
                                  children: [],
                                },
                                {
                                  id: generateId(),
                                  type: 'ea-text',
                                  props: { children: '更新产品库存信息' },
                                  slots: {},
                                  style: {
                                    display: 'block',
                                    padding: '6px 0',
                                    fontSize: '14px',
                                  },
                                  events: [],
                                  children: [],
                                },
                              ],
                            },
                            {
                              id: generateId(),
                              type: 'ea-collapse-item',
                              props: { title: '本周计划 (2)', name: 'week' },
                              slots: {},
                              style: {},
                              events: [],
                              children: [
                                {
                                  id: generateId(),
                                  type: 'ea-text',
                                  props: { children: '完成季度销售报告' },
                                  slots: {},
                                  style: {
                                    display: 'block',
                                    padding: '6px 0',
                                    fontSize: '14px',
                                  },
                                  events: [],
                                  children: [],
                                },
                                {
                                  id: generateId(),
                                  type: 'ea-text',
                                  props: { children: '组织团队周会' },
                                  slots: {},
                                  style: {
                                    display: 'block',
                                    padding: '6px 0',
                                    fontSize: '14px',
                                  },
                                  events: [],
                                  children: [],
                                },
                              ],
                            },
                          ],
                        },
                      ],
                    },
                  ],
                },
              ],
            },
            {
              id: generateId(),
              type: 'ea-row',
              props: { gutter: 16 },
              slots: {},
              style: {},
              events: [],
              children: [
                {
                  id: generateId(),
                  type: 'ea-col',
                  props: { span: 12 },
                  slots: {},
                  style: {},
                  events: [],
                  children: [
                    {
                      id: generateId(),
                      type: 'ea-card',
                      props: { shadow: 'always' },
                      slots: {},
                      style: { borderRadius: '8px' },
                      events: [],
                      children: [
                        {
                          id: generateId(),
                          type: 'ea-text',
                          props: {
                            slot: 'header',
                            children: '系统公告',
                            size: 'medium',
                          },
                          slots: {},
                          style: {
                            fontWeight: '600',
                            padding: '16px 20px',
                            borderBottom: '1px solid #f0f0f0',
                          },
                          events: [],
                          children: [],
                        },
                        {
                          id: generateId(),
                          type: 'ea-descriptions',
                          props: { column: 1, border: true },
                          slots: {},
                          style: {},
                          events: [],
                          children: [
                            {
                              id: generateId(),
                              type: 'ea-descriptions-item',
                              props: {
                                label: '2024-01-15',
                                children:
                                  '系统将于本周六凌晨2:00-4:00进行维护升级，届时服务将暂停访问。',
                              },
                              slots: {},
                              style: {},
                              events: [],
                              children: [],
                            },
                            {
                              id: generateId(),
                              type: 'ea-descriptions-item',
                              props: {
                                label: '2024-01-12',
                                children:
                                  '新版本v2.5.0已发布，新增数据导出功能和性能优化。',
                              },
                              slots: {},
                              style: {},
                              events: [],
                              children: [],
                            },
                            {
                              id: generateId(),
                              type: 'ea-descriptions-item',
                              props: {
                                label: '2024-01-10',
                                children:
                                  '请各位同事及时更新个人资料，确保联系方式准确无误。',
                              },
                              slots: {},
                              style: {},
                              events: [],
                              children: [],
                            },
                          ],
                        },
                      ],
                    },
                  ],
                },
                {
                  id: generateId(),
                  type: 'ea-col',
                  props: { span: 12 },
                  slots: {},
                  style: {},
                  events: [],
                  children: [
                    {
                      id: generateId(),
                      type: 'ea-card',
                      props: { shadow: 'always' },
                      slots: {},
                      style: { borderRadius: '8px' },
                      events: [],
                      children: [
                        {
                          id: generateId(),
                          type: 'ea-text',
                          props: {
                            slot: 'header',
                            children: '快捷操作',
                            size: 'medium',
                          },
                          slots: {},
                          style: {
                            fontWeight: '600',
                            padding: '16px 20px',
                            borderBottom: '1px solid #f0f0f0',
                          },
                          events: [],
                          children: [],
                        },
                        {
                          id: generateId(),
                          type: 'ea-row',
                          props: { gutter: 16 },
                          slots: {},
                          style: { padding: '16px 0' },
                          events: [],
                          children: [
                            {
                              id: generateId(),
                              type: 'ea-col',
                              props: { span: 6 },
                              slots: {},
                              style: {
                                textAlign: 'center',
                                marginBottom: '12px',
                              },
                              events: [],
                              children: [
                                {
                                  id: generateId(),
                                  type: 'ea-button',
                                  props: {
                                    icon: 'user-plus',
                                    children: '新增用户',
                                    type: 'primary',
                                  },
                                  slots: {},
                                  style: { width: '100%' },
                                  events: [],
                                  children: [],
                                },
                              ],
                            },
                            {
                              id: generateId(),
                              type: 'ea-col',
                              props: { span: 6 },
                              slots: {},
                              style: {
                                textAlign: 'center',
                                marginBottom: '12px',
                              },
                              events: [],
                              children: [
                                {
                                  id: generateId(),
                                  type: 'ea-button',
                                  props: {
                                    icon: 'file-lines',
                                    children: '新建文档',
                                    type: 'success',
                                  },
                                  slots: {},
                                  style: { width: '100%' },
                                  events: [],
                                  children: [],
                                },
                              ],
                            },
                            {
                              id: generateId(),
                              type: 'ea-col',
                              props: { span: 6 },
                              slots: {},
                              style: {
                                textAlign: 'center',
                                marginBottom: '12px',
                              },
                              events: [],
                              children: [
                                {
                                  id: generateId(),
                                  type: 'ea-button',
                                  props: {
                                    icon: 'chart-simple',
                                    children: '数据报表',
                                    type: 'warning',
                                  },
                                  slots: {},
                                  style: { width: '100%' },
                                  events: [],
                                  children: [],
                                },
                              ],
                            },
                            {
                              id: generateId(),
                              type: 'ea-col',
                              props: { span: 6 },
                              slots: {},
                              style: {
                                textAlign: 'center',
                                marginBottom: '12px',
                              },
                              events: [],
                              children: [
                                {
                                  id: generateId(),
                                  type: 'ea-button',
                                  props: {
                                    icon: 'gear',
                                    children: '系统设置',
                                    type: 'danger',
                                  },
                                  slots: {},
                                  style: { width: '100%' },
                                  events: [],
                                  children: [],
                                },
                              ],
                            },
                          ],
                        },
                      ],
                    },
                  ],
                },
              ],
            },
          ],
        },
      ],
      variables: [
        {
          id: generateId().replace('comp_', 'var_'),
          name: 'orderData',
          type: 'array',
          defaultValue: [
            {
              orderNo: 'ORD-20240115-001',
              customer: '张三',
              amount: '¥12,800.00',
              status: '已完成',
              createdAt: '2024-01-15 10:30',
            },
            {
              orderNo: 'ORD-20240114-002',
              customer: '李四',
              amount: '¥5,600.50',
              status: '处理中',
              createdAt: '2024-01-14 16:20',
            },
            {
              orderNo: 'ORD-20240114-003',
              customer: '王五',
              amount: '¥23,400.00',
              status: '已完成',
              createdAt: '2024-01-14 09:15',
            },
            {
              orderNo: 'ORD-20240113-004',
              customer: '赵六',
              amount: '¥8,900.00',
              status: '待付款',
              createdAt: '2024-01-13 14:45',
            },
          ],
          remark: '',
        },
      ],
      settings: {
        events: [
          {
            id: generateId().replace('comp_', 'event_'),
            name: 'initPage',
            eventType: 'load',
            customEventType: 'load',
            action: 'custom',
            actionConfig: {
              code: '// 页面初始化：填充订单表格数据\nconst orderData = $vars.get("orderData");\n$alias.setProp("orderTable", "data", orderData);',
            },
          },
        ],
      },
    },
  },

  form: {
    name: '表单页面',
    schema: {
      meta: {
        title: '表单页面',
        description: '',
      },
      layout: {
        type: 'absolute',
        config: {},
      },
      version: '1.0',
      components: [
        {
          id: 'comp_1776532057997_731bkk04',
          type: 'ea-container',
          props: {
            direction: 'vertical',
          },
          slots: {},
          style: {
            padding: '20px',
            minHeight: '100vh',
            backgroundColor: '#f5f7fa',
          },
          events: [],
          children: [
            {
              id: 'comp_1776532057997_g02bzj6y',
              type: 'ea-card',
              props: {
                header: '信息录入',
              },
              slots: {},
              style: {
                width: '100%',
                margin: '0 auto',
                maxWidth: '800px',
                borderRadius: '8px',
              },
              events: [],
              children: [
                {
                  id: 'comp_1776532057997_il4t1pd7',
                  type: 'form',
                  props: {
                    action: '/api/form/submit',
                    method: 'post',
                    enctype: 'application/x-www-form-urlencoded',
                  },
                  slots: {},
                  style: {
                    padding: '20px',
                  },
                  events: [
                    {
                      id: 'event_1776532292808_8rg9arkb',
                      name: 'event1',
                      eventType: 'submit',
                      customEventType: 'submit',
                      action: 'message',
                      actionConfig: {
                        message: '提交成功',
                        type: 'success',
                        duration: 3000,
                        showClose: false,
                        dangerouslyUseHTMLString: false,
                        placement: 'top',
                        offset: 16,
                      },
                    },
                    {
                      id: 'event_1776532326655_7ydiyubu',
                      name: 'event2',
                      eventType: 'reset',
                      customEventType: 'reset',
                      action: 'message',
                      actionConfig: {
                        message: '重置表单',
                        type: 'info',
                        duration: 3000,
                        showClose: false,
                        dangerouslyUseHTMLString: false,
                        placement: 'top',
                        offset: 16,
                      },
                    },
                  ],
                  children: [
                    {
                      id: 'comp_1776532057997_izg8pjtk',
                      type: 'ea-row',
                      props: {
                        gutter: 20,
                      },
                      slots: {},
                      style: {
                        marginBottom: '16px',
                      },
                      events: [],
                      children: [
                        {
                          id: 'comp_1776532057997_vf0bee31',
                          type: 'ea-col',
                          props: {
                            span: 12,
                          },
                          slots: {},
                          style: {},
                          events: [],
                          children: [
                            {
                              id: 'comp_1776532057997_8k5rq40g',
                              type: 'ea-input',
                              props: {
                                name: 'name',
                                label: '姓名',
                                required: true,
                                clearable: true,
                                maxlength: 20,
                                minlength: 2,
                                placeholder: '请输入姓名',
                                autocomplete: 'off',
                                showWordLimit: true,
                              },
                              slots: {},
                              style: {},
                              events: [],
                              children: [],
                            },
                          ],
                        },
                        {
                          id: 'comp_1776532057997_4snqj5zn',
                          type: 'ea-col',
                          props: {
                            span: 12,
                          },
                          slots: {},
                          style: {},
                          events: [],
                          children: [
                            {
                              id: 'comp_1776532057997_3gx0sszp',
                              type: 'ea-input',
                              props: {
                                name: 'email',
                                type: 'email',
                                label: '邮箱',
                                pattern:
                                  '^[a-zA-Z0-9._%+-]+@[a-zA-Z0-9.-]+\\.[a-zA-Z]{2,}$',
                                required: true,
                                clearable: true,
                                placeholder: '请输入邮箱地址',
                              },
                              slots: {},
                              style: {},
                              events: [],
                              children: [],
                            },
                          ],
                        },
                      ],
                    },
                    {
                      id: 'comp_1776532057997_hwlch2v7',
                      type: 'ea-row',
                      props: {
                        gutter: 20,
                      },
                      slots: {},
                      style: {
                        marginBottom: '16px',
                      },
                      events: [],
                      children: [
                        {
                          id: 'comp_1776532057997_f1u3ml3p',
                          type: 'ea-col',
                          props: {
                            span: 12,
                          },
                          slots: {},
                          style: {},
                          events: [],
                          children: [
                            {
                              id: 'comp_1776532057997_sn0e8dzm',
                              type: 'ea-input',
                              props: {
                                name: 'phone',
                                type: 'tel',
                                label: '手机号',
                                pattern: '^1[3-9]\\d{9}$',
                                required: true,
                                clearable: true,
                                maxlength: 11,
                                placeholder: '请输入11位手机号',
                              },
                              slots: {},
                              style: {},
                              events: [],
                              children: [],
                            },
                          ],
                        },
                        {
                          id: 'comp_1776532057997_x0vyw0vz',
                          type: 'ea-col',
                          props: {
                            span: 12,
                          },
                          slots: {},
                          style: {},
                          events: [],
                          children: [
                            {
                              id: 'comp_1776532057997_7gfa6gy2',
                              type: 'ea-select',
                              props: {
                                name: 'department',
                                label: '部门',
                                required: true,
                                clearable: true,
                                filterable: true,
                                placeholder: '请选择部门',
                              },
                              slots: {},
                              style: {},
                              events: [],
                              children: [
                                {
                                  id: 'comp_1776532057997_pblpllzx',
                                  type: 'ea-option',
                                  props: {
                                    slot: 'default',
                                    value: 'frontend',
                                  },
                                  slots: {},
                                  childrenText: '前端开发部',
                                },
                                {
                                  id: 'comp_1776532057997_19qzkvln',
                                  type: 'ea-option',
                                  props: {
                                    slot: 'default',
                                    value: 'backend',
                                  },
                                  slots: {},
                                  childrenText: '后端开发部',
                                },
                                {
                                  id: 'comp_1776532057997_8epmzkva',
                                  type: 'ea-option',
                                  props: {
                                    slot: 'default',
                                    value: 'design',
                                  },
                                  slots: {},
                                  childrenText: '设计部',
                                },
                                {
                                  id: 'comp_1776532057997_49bfxz8v',
                                  type: 'ea-option',
                                  props: {
                                    slot: 'default',
                                    value: 'product',
                                  },
                                  slots: {},
                                  childrenText: '产品部',
                                },
                              ],
                            },
                          ],
                        },
                      ],
                    },
                    {
                      id: 'comp_1776532057997_faql357k',
                      type: 'ea-row',
                      props: {
                        gutter: 20,
                      },
                      slots: {},
                      style: {
                        marginBottom: '16px',
                      },
                      events: [],
                      children: [
                        {
                          id: 'comp_1776532057997_nkutri0l',
                          type: 'ea-col',
                          props: {
                            span: 12,
                          },
                          slots: {},
                          style: {},
                          events: [],
                          children: [
                            {
                              id: 'comp_1776532057997_f0lgj44p',
                              type: 'ea-input',
                              props: {
                                max: 65,
                                min: 18,
                                name: 'age',
                                type: 'number',
                                label: '年龄',
                                placeholder: '请输入年龄',
                              },
                              slots: {},
                              style: {},
                              events: [],
                              children: [],
                            },
                          ],
                        },
                        {
                          id: 'comp_1776532057997_ruuopg0e',
                          type: 'ea-col',
                          props: {
                            span: 12,
                          },
                          slots: {},
                          style: {},
                          events: [],
                          children: [
                            {
                              id: 'comp_1776532057997_8vypte88',
                              type: 'ea-input',
                              props: {
                                name: 'password',
                                type: 'password',
                                label: '密码',
                                required: true,
                                maxlength: 20,
                                minlength: 6,
                                placeholder: '请设置登录密码（6-20位）',
                                autocomplete: 'new-password',
                                showPassword: true,
                              },
                              slots: {},
                              style: {},
                              events: [],
                              children: [],
                            },
                          ],
                        },
                      ],
                    },
                    {
                      id: 'comp_1776532057997_nahlijq6',
                      type: 'ea-input',
                      props: {
                        name: 'remark',
                        rows: 4,
                        type: 'textarea',
                        label: '备注说明',
                        resize: 'vertical',
                        maxlength: 500,
                        placeholder: '请输入备注信息',
                        showWordLimit: true,
                      },
                      slots: {},
                      style: {
                        marginBottom: '16px',
                      },
                      events: [],
                      children: [],
                    },
                    {
                      id: 'comp_1776532057997_c44hnlyx',
                      type: 'ea-button-group',
                      props: {},
                      slots: {},
                      style: {
                        gap: '12px',
                        display: 'flex',
                        justifyContent: 'flex-end',
                      },
                      events: [],
                      children: [
                        {
                          id: 'comp_1776532057997_rspu7wyt',
                          type: 'ea-button',
                          props: {
                            type: 'default',
                            children: '重置',
                            'button-type': 'reset',
                          },
                          slots: {},
                          style: {},
                          events: [
                            {
                              eventType: 'click',
                              handlerType: 'resetForm',
                            },
                          ],
                          children: [],
                        },
                        {
                          id: 'comp_1776532057997_cgciirav',
                          type: 'ea-button',
                          props: {
                            type: 'primary',
                            children: '提交',
                            'button-type': 'submit',
                          },
                          slots: {},
                          style: {},
                          events: [
                            {
                              eventType: 'click',
                              handlerType: 'submitForm',
                            },
                          ],
                          children: [],
                        },
                      ],
                    },
                  ],
                },
              ],
            },
          ],
        },
      ],
      variables: [],
    },
  },

  list: {
    name: '列表页面',
    schema: {
      meta: {
        title: '列表页面',
        description: '',
      },
      layout: {
        type: 'absolute',
        config: {},
      },
      version: '1.0',
      components: [
        {
          id: 'comp_1776535005883_se01s39u',
          type: 'ea-container',
          props: {
            direction: 'vertical',
          },
          slots: {},
          style: {
            padding: '20px',
            minHeight: '100vh',
            backgroundColor: '#f5f7fa',
          },
          events: [],
          children: [
            {
              id: 'comp_1776535005883_4c13jzey',
              type: 'ea-row',
              props: {
                gutter: 16,
              },
              slots: {},
              style: {
                marginBottom: '16px',
              },
              events: [],
              children: [
                {
                  id: 'comp_1776535005883_kz82s8s8',
                  type: 'ea-col',
                  props: {
                    span: 6,
                  },
                  slots: {},
                  style: {},
                  events: [],
                  children: [
                    {
                      id: 'comp_1776535005883_4448mixb',
                      type: 'ea-card',
                      props: {
                        shadow: 'hover',
                      },
                      slots: {},
                      style: {
                        padding: '16px',
                        textAlign: 'center',
                      },
                      events: [],
                      children: [
                        {
                          id: 'comp_1776535005883_kb8jw0v8',
                          type: 'ea-statistic',
                          props: {
                            title: '总用户数',
                            value: '26800',
                          },
                          slots: {},
                          style: {},
                          events: [],
                          children: [],
                        },
                      ],
                    },
                  ],
                },
                {
                  id: 'comp_1776535005883_nue5yt0z',
                  type: 'ea-col',
                  props: {
                    span: 6,
                  },
                  slots: {},
                  style: {},
                  events: [],
                  children: [
                    {
                      id: 'comp_1776535005883_b29w29al',
                      type: 'ea-card',
                      props: {
                        shadow: 'hover',
                      },
                      slots: {},
                      style: {
                        padding: '16px',
                        textAlign: 'center',
                      },
                      events: [],
                      children: [
                        {
                          id: 'comp_1776535005883_sm1shjy0',
                          type: 'ea-statistic',
                          props: {
                            title: '今日访问',
                            value: '1234',
                          },
                          slots: {},
                          style: {},
                          events: [],
                          children: [],
                        },
                      ],
                    },
                  ],
                },
                {
                  id: 'comp_1776535005883_8kouysgf',
                  type: 'ea-col',
                  props: {
                    span: 6,
                  },
                  slots: {},
                  style: {},
                  events: [],
                  children: [
                    {
                      id: 'comp_1776535005883_pgxdjtcb',
                      type: 'ea-card',
                      props: {
                        shadow: 'hover',
                      },
                      slots: {},
                      style: {
                        padding: '16px',
                        textAlign: 'center',
                      },
                      events: [],
                      children: [
                        {
                          id: 'comp_1776535005883_s0c2z2sn',
                          type: 'ea-statistic',
                          props: {
                            title: '活跃用户',
                            value: '8900',
                          },
                          slots: {},
                          style: {},
                          events: [],
                          children: [],
                        },
                      ],
                    },
                  ],
                },
                {
                  id: 'comp_1776535005883_mrm6tlc4',
                  type: 'ea-col',
                  props: {
                    span: 6,
                  },
                  slots: {},
                  style: {},
                  events: [],
                  children: [
                    {
                      id: 'comp_1776535005883_b8xfj05v',
                      type: 'ea-card',
                      props: {
                        shadow: 'hover',
                      },
                      slots: {},
                      style: {
                        padding: '16px',
                        textAlign: 'center',
                      },
                      events: [],
                      children: [
                        {
                          id: 'comp_1776535005883_wc1zxx9o',
                          type: 'ea-statistic',
                          props: {
                            title: '转化率',
                            value: '68.5',
                          },
                          slots: {},
                          style: {},
                          events: [],
                          children: [
                            {
                              id: 'comp_1776535005883_cy51k8vd',
                              type: 'ea-text',
                              props: {
                                size: 'small',
                                slot: 'suffix',
                                children: '%',
                              },
                              slots: {},
                              style: {},
                              events: [],
                              children: [],
                            },
                          ],
                        },
                      ],
                    },
                  ],
                },
              ],
            },
            {
              id: 'comp_1776535005883_rcs4kuqj',
              type: 'ea-card',
              props: {
                header: '数据列表',
                shadow: 'always',
              },
              slots: {},
              style: {
                borderRadius: '8px',
              },
              events: [],
              children: [
                {
                  id: 'comp_1776535005883_6puk20ba',
                  type: 'ea-row',
                  props: {
                    gutter: 16,
                  },
                  slots: {},
                  style: {
                    padding: '0 4px',
                    marginBottom: '16px',
                  },
                  events: [],
                  children: [
                    {
                      id: 'comp_1776535005883_d3on7ni8',
                      type: 'ea-col',
                      props: {
                        span: 8,
                      },
                      slots: {},
                      style: {},
                      events: [],
                      children: [
                        {
                          id: 'comp_1776535005883_rbf2mn8q',
                          type: 'ea-input',
                          props: {
                            clearable: true,
                            prefixIcon: 'magnifying-glass',
                            placeholder: '请输入搜索关键词',
                          },
                          slots: {},
                          style: {},
                          events: [],
                          children: [],
                        },
                      ],
                    },
                    {
                      id: 'comp_1776535005883_7jyfuywp',
                      type: 'ea-col',
                      props: {
                        span: 16,
                      },
                      slots: {},
                      style: {
                        gap: '8px',
                        display: 'flex',
                        justifyContent: 'flex-end',
                      },
                      events: [],
                      children: [
                        {
                          id: 'comp_1776535005883_ok26iy1n',
                          type: 'ea-button',
                          props: {
                            icon: 'magnifying-glass',
                            type: 'primary',
                            children: '搜索',
                          },
                          slots: {},
                          style: {},
                          events: [],
                          children: [],
                        },
                        {
                          id: 'comp_1776535005883_0rrrimzy',
                          type: 'ea-button',
                          props: {
                            icon: 'rotate-left',
                            children: '重置',
                          },
                          slots: {},
                          style: {},
                          events: [],
                          children: [],
                        },
                        {
                          id: 'comp_1776535005883_yz7vi180',
                          type: 'ea-button',
                          props: {
                            icon: 'plus',
                            type: 'success',
                            children: '新增',
                          },
                          slots: {},
                          style: {},
                          events: [],
                          children: [],
                        },
                      ],
                    },
                  ],
                },
                {
                  id: 'comp_1776535005883_t3unbb0n',
                  type: 'ea-table',
                  props: {
                    border: true,
                    stripe: true,
                  },
                  slots: {},
                  style: {
                    width: '100%',
                  },
                  events: [
                    {
                      id: 'event_1776535540505_a2dywrdy',
                      name: 'event1',
                      eventType: 'load',
                      customEventType: 'load',
                      action: 'custom',
                      actionConfig: {
                        code: '// 使用 $component 操作其他组件\n// 示例：设置按钮 loading\nconst tableData = $vars.get("tableData");\n$alias.setProp(\'table\', "data", tableData);\n$component.setProp("comp_1776535005883_t3unbb0n", "data", tableData)\nconsole.log($alias.getElement("table"))',
                      },
                    },
                  ],
                  children: [
                    {
                      id: 'comp_1776535005883_fu0buqop',
                      type: 'ea-table-column',
                      props: {
                        type: 'index',
                        align: 'center',
                        label: '序号',
                        width: '80px',
                      },
                      slots: {},
                      style: {},
                      events: [],
                      children: [],
                    },
                    {
                      id: 'comp_1776535005883_1jj1wr1s',
                      type: 'ea-table-column',
                      props: {
                        prop: 'name',
                        label: '名称',
                        width: '180px',
                      },
                      slots: {},
                      style: {},
                      events: [],
                      children: [],
                    },
                    {
                      id: 'comp_1776535005883_5h23puqx',
                      type: 'ea-table-column',
                      props: {
                        prop: 'status',
                        align: 'center',
                        label: '状态',
                        width: '120px',
                      },
                      slots: {},
                      style: {},
                      events: [],
                      children: [],
                    },
                    {
                      id: 'comp_1776535005883_fm5ek9wn',
                      type: 'ea-table-column',
                      props: {
                        prop: 'createdAt',
                        align: 'center',
                        label: '创建时间',
                        width: '180px',
                      },
                      slots: {},
                      style: {},
                      events: [],
                      children: [],
                    },
                    {
                      id: 'comp_1776535005883_a93rxjrm',
                      type: 'ea-table-column',
                      props: {
                        align: 'center',
                        label: '操作',
                        width: '200px',
                      },
                      slots: {},
                      style: {},
                      events: [],
                      children: [],
                    },
                  ],
                  alias: 'table',
                },
                {
                  id: 'comp_1776535005883_gumednwj',
                  type: 'ea-pagination',
                  props: {
                    total: 100,
                    pageSize: 10,
                    background: true,
                  },
                  slots: {},
                  style: {
                    display: 'flex',
                    marginTop: '16px',
                    justifyContent: 'flex-end',
                  },
                  events: [],
                  children: [],
                },
              ],
            },
          ],
        },
      ],
      variables: [
        {
          id: 'var_1776535065151_0q2mi9ai',
          name: 'tableData',
          type: 'array',
          defaultValue: [
            {
              date: '2016-05-03',
              name: 'Tom',
              address: 'No. 189, Grove St, Los Angeles',
            },
            {
              date: '2016-05-02',
              name: 'Tom',
              address: 'No. 189, Grove St, Los Angeles',
            },
            {
              date: '2016-05-04',
              name: 'Tom',
              address: 'No. 189, Grove St, Los Angeles',
            },
            {
              date: '2016-05-01',
              name: 'Tom',
              address: 'No. 189, Grove St, Los Angeles',
            },
          ],
          remark: '',
        },
      ],
      settings: {
        events: [
          {
            id: 'event_1776535180533_lqdh1z6d',
            name: 'setTableData',
            eventType: 'load',
            customEventType: 'load',
            action: 'custom',
            actionConfig: {
              code: '// 使用 $component 操作其他组件\n// 示例：设置按钮 loading\nconst tableData = $vars.get("tableData");\n$alias.setProp(\'table\', "data", tableData);\n$component.setProp("comp_1776535005883_t3unbb0n", "data", tableData)\nconsole.log($alias.getElement("table"))',
            },
          },
        ],
      },
    },
  },

  detail: {
    name: '详情页面',
    schema: {
      meta: {
        title: '详情页面',
        description: '',
      },
      layout: {
        type: 'absolute',
        config: {},
      },
      version: '1.0',
      settings: {
        style: {
          width: '',
        },
      },
      variables: [],
      components: [
        {
          id: 'comp_1776532472876_2wixl3z9',
          type: 'ea-container',
          props: {
            direction: 'vertical',
          },
          slots: {},
          style: {
            padding: '20px',
            minHeight: '100vh',
            backgroundColor: '#ffffff',
          },
          events: [],
          children: [
            {
              id: 'comp_1776532627151_86eykhbb',
              type: 'ea-header',
              props: {
                height: 'auto',
              },
              style: {},
              events: [],
              children: [
                {
                  id: 'comp_1776532674022_34i5imm4',
                  type: 'ea-page-header',
                  props: {
                    icon: 'angle-left',
                    title: 'Back',
                    content: '详情页',
                  },
                  style: {},
                  events: [],
                  children: [],
                },
              ],
            },
            {
              id: 'comp_1776532629865_mmyfjiq2',
              type: 'ea-main',
              props: {},
              style: {
                padding: '16px 0px',
              },
              events: [],
              children: [
                {
                  id: 'comp_1776532885146_u81hvor2',
                  type: 'ea-card',
                  props: {
                    footer: '',
                    header: '',
                    shadow: 'hover',
                  },
                  style: {},
                  events: [],
                  children: [
                    {
                      id: 'comp_1776533187331_nktxhag1',
                      type: 'ea-descriptions',
                      props: {
                        size: 'small',
                        title: '',
                        border: false,
                        column: 3,
                        direction: 'vertical',
                        'label-width': '150px',
                      },
                      style: {
                        width: '1px',
                      },
                      events: [],
                      children: [
                        {
                          id: 'comp_1776533757615_y4xyhk70',
                          type: 'ea-descriptions-item',
                          props: {
                            align: '',
                            label: 'Avatar',
                            width: '',
                            colspan: 1,
                            rowspan: 1,
                            children: '',
                            'label-part': '',
                            'label-align': '',
                            'label-width': '',
                            'content-part': '',
                          },
                          style: {},
                          events: [],
                          children: [
                            {
                              id: 'comp_1776533807745_37aamlqy',
                              type: 'ea-avatar',
                              props: {
                                alt: '',
                                fit: 'cover',
                                src: '',
                                icon: '',
                                size: 'default',
                                shape: 'circle',
                                'src-set': '',
                              },
                              style: {},
                              events: [],
                              children: [],
                            },
                          ],
                        },
                        {
                          id: 'comp_1776533192893_u5sht8zi',
                          type: 'ea-descriptions-item',
                          props: {
                            align: '',
                            label: 'Username',
                            width: '',
                            colspan: 1,
                            rowspan: 1,
                            children: 'Lilyiro ',
                            'label-part': '',
                            'label-align': '',
                            'label-width': '',
                            'content-part': '',
                          },
                          style: {},
                          events: [],
                          children: [],
                        },
                        {
                          id: 'comp_1776533256303_hmlz6577',
                          type: 'ea-descriptions-item',
                          props: {
                            align: '',
                            label: 'Essence',
                            width: '',
                            colspan: 1,
                            rowspan: 1,
                            children: 'Lord of the Wild',
                            'label-part': '',
                            'label-align': '',
                            'label-width': '',
                            'content-part': '',
                          },
                          style: {},
                          events: [],
                          children: [],
                        },
                        {
                          id: 'comp_1776533308807_ck5r45cu',
                          type: 'ea-descriptions-item',
                          props: {
                            align: '',
                            label: 'Place',
                            width: '',
                            colspan: 1,
                            rowspan: 1,
                            children: 'Lunacrest Continent',
                            'label-part': '',
                            'label-align': '',
                            'label-width': '',
                            'content-part': '',
                          },
                          style: {},
                          events: [],
                          children: [],
                        },
                        {
                          id: 'comp_1776533580059_hwcew4hr',
                          type: 'ea-descriptions-item',
                          props: {
                            align: '',
                            label: 'Traits',
                            width: '',
                            colspan: 1,
                            rowspan: 1,
                            children: '',
                            'label-part': '',
                            'label-align': '',
                            'label-width': '',
                            'content-part': '',
                          },
                          style: {},
                          events: [],
                          children: [
                            {
                              id: 'comp_1776533613734_o9om3v1i',
                              type: 'ea-tag',
                              props: {
                                size: 'default',
                                type: 'warning',
                                color: '',
                                round: false,
                                effect: 'light',
                                children: 'Thunderous Veins',
                                closable: false,
                                'disable-transitions': false,
                              },
                              style: {},
                              events: [],
                              children: [],
                            },
                            {
                              id: 'comp_1776533647349_enotpwns',
                              type: 'ea-tag',
                              props: {
                                size: 'default',
                                type: 'info',
                                color: '',
                                round: false,
                                effect: 'light',
                                children: 'Daredevil',
                                closable: false,
                                'disable-transitions': false,
                              },
                              style: {},
                              events: [],
                              children: [],
                            },
                          ],
                        },
                        {
                          id: 'comp_1776533582897_7c8kbu3w',
                          type: 'ea-descriptions-item',
                          props: {
                            align: '',
                            label: 'Description',
                            width: '',
                            colspan: 1,
                            rowspan: 1,
                            children: '',
                            'label-part': '',
                            'label-align': '',
                            'label-width': '',
                            'content-part': '',
                          },
                          style: {},
                          events: [],
                          children: [
                            {
                              id: 'comp_1776533690387_qve3v1zi',
                              type: 'ea-text',
                              props: {
                                tag: 'span',
                                size: 'medium',
                                type: 'normal',
                                title: '',
                                children:
                                  '      She was once an elf lord, defending the border from goblin invaders. She       was then a goblin warrior, protecting her clan from being slaughtered by       elves. She has the unwavering courage to uphold justice in her heart and       she is prepared to betray or be betrayed for the greater good. Despite her       inner gentleness, Lilyiro, who has spilled so much blood on battlefields,       is more straightforward than men.',
                                truncated: false,
                                'line-clamp': 0,
                              },
                              style: {},
                              events: [],
                              children: [],
                            },
                          ],
                        },
                      ],
                    },
                  ],
                },
              ],
            },
            {
              id: 'comp_1776532631412_6um8rqcm',
              type: 'ea-footer',
              props: {
                height: 'auto',
              },
              style: {},
              events: [],
              children: [
                {
                  id: 'comp_1776534118623_ekoqay74',
                  type: 'ea-space',
                  props: {
                    fill: false,
                    size: 'small',
                    wrap: false,
                    spacer: ' | ',
                    alignment: 'center',
                    direction: 'horizontal',
                    'fill-ratio': 0,
                  },
                  style: {},
                  events: [],
                  children: [
                    {
                      id: 'comp_1776534124076_f42il9jj',
                      type: 'ea-text',
                      props: {
                        tag: 'span',
                        size: 'medium',
                        type: 'normal',
                        title: '',
                        children: 'LuminaQAQ',
                        truncated: false,
                        'line-clamp': 0,
                      },
                      style: {},
                      events: [],
                      children: [],
                    },
                    {
                      id: 'comp_1776534360586_6ic7gzg3',
                      type: 'ea-link',
                      props: {
                        children: 'Github',
                        type: 'info',
                        disabled: false,
                        underline: '',
                        href: 'https://github.com/LuminaQAQ',
                        icon: 'coffee',
                      },
                      style: {},
                      events: [],
                      children: [],
                    },
                  ],
                },
              ],
            },
          ],
        },
      ],
    },
  },
};

export function getTemplateSchema(templateId: string): any | null {
  const template = TEMPLATES[templateId];
  return template ? JSON.parse(JSON.stringify(template.schema)) : null;
}
