import { ComponentCategories, PropTypes } from '../types'

// Form 表单组件
export const formComponents = [
  {
    type: 'form',
    name: '表单',
    category: ComponentCategories.FORM,
    icon: 'Form',
    props: [
      {
        name: 'action',
        label: '提交地址',
        type: PropTypes.STRING,
        default: '',
      },
      {
        name: 'method',
        label: '提交方法',
        type: PropTypes.SELECT,
        default: 'get',
        options: [
          { label: 'GET', value: 'get' },
          { label: 'POST', value: 'post' },
        ],
      },
      {
        name: 'enctype',
        label: '编码类型',
        type: PropTypes.SELECT,
        default: 'application/x-www-form-urlencoded',
        options: [
          { label: 'URL编码', value: 'application/x-www-form-urlencoded' },
          { label: '表单数据', value: 'multipart/form-data' },
          { label: '纯文本', value: 'text/plain' },
        ],
      },
      {
        name: 'target',
        label: '提交目标',
        type: PropTypes.SELECT,
        default: '_self',
        options: [
          { label: '当前窗口', value: '_self' },
          { label: '新窗口', value: '_blank' },
          { label: '父窗口', value: '_parent' },
          { label: '顶层窗口', value: '_top' },
        ],
      },
      {
        name: 'novalidate',
        label: '禁用验证',
        type: PropTypes.BOOLEAN,
        default: false,
      },
    ],
    events: [
      { name: 'submit', label: '提交事件' },
      { name: 'reset', label: '重置事件' },
      { name: 'change', label: '改变事件' },
      { name: 'input', label: '输入事件' },
    ],
    slots: [{ name: 'default', label: '表单内容' }],
  },
  {
    type: 'ea-input',
    name: '输入框',
    category: ComponentCategories.FORM,
    icon: 'Input',
    props: [
      {
        name: 'type',
        label: '输入框类型',
        type: PropTypes.SELECT,
        default: 'text',
        options: [
          { label: '文本', value: 'text' },
          { label: '密码', value: 'password' },
          { label: '多行文本', value: 'textarea' },
          { label: '数字', value: 'number' },
          { label: '日期', value: 'date' },
          { label: '时间', value: 'time' },
          { label: '邮箱', value: 'email' },
          { label: '电话', value: 'tel' },
          { label: '链接', value: 'url' },
        ],
      },
      {
        name: 'value',
        label: '输入框值',
        type: PropTypes.STRING,
        default: '',
      },
      {
        name: 'placeholder',
        label: '占位符',
        type: PropTypes.STRING,
        default: '',
      },
      {
        name: 'disabled',
        label: '禁用',
        type: PropTypes.BOOLEAN,
        default: false,
      },
      {
        name: 'clearable',
        label: '可清空',
        type: PropTypes.BOOLEAN,
        default: false,
      },
      {
        name: 'clear-icon',
        label: '清除图标',
        type: PropTypes.STRING,
        default: 'icon-cancel',
      },
      {
        name: 'show-password',
        label: '显示密码切换',
        type: PropTypes.BOOLEAN,
        default: false,
      },
      {
        name: 'prefix-icon',
        label: '前缀图标',
        type: PropTypes.STRING,
        default: '',
      },
      {
        name: 'suffix-icon',
        label: '后缀图标',
        type: PropTypes.STRING,
        default: '',
      },
      {
        name: 'rows',
        label: '文本域行数',
        type: PropTypes.NUMBER,
        default: 2,
      },
      {
        name: 'autosize',
        label: '自适应高度',
        type: PropTypes.BOOLEAN,
        default: false,
      },
      {
        name: 'min-rows',
        label: '最小行数',
        type: PropTypes.NUMBER,
        default: 0,
      },
      {
        name: 'max-rows',
        label: '最大行数',
        type: PropTypes.NUMBER,
        default: 0,
      },
      {
        name: 'maxlength',
        label: '最大长度',
        type: PropTypes.NUMBER,
        default: 0,
      },
      {
        name: 'minlength',
        label: '最小长度',
        type: PropTypes.NUMBER,
        default: 0,
      },
      {
        name: 'show-word-limit',
        label: '显示字数统计',
        type: PropTypes.BOOLEAN,
        default: false,
      },
      {
        name: 'autocomplete',
        label: '自动完成',
        type: PropTypes.SELECT,
        default: 'off',
        options: [
          { label: '开启', value: 'on' },
          { label: '关闭', value: 'off' },
        ],
      },
      {
        name: 'name',
        label: 'name属性',
        type: PropTypes.STRING,
        default: '',
      },
      {
        name: 'readonly',
        label: '只读',
        type: PropTypes.BOOLEAN,
        default: false,
      },
      {
        name: 'max',
        label: '最大值',
        type: PropTypes.NUMBER,
        default: 9007199254740991,
      },
      {
        name: 'min',
        label: '最小值',
        type: PropTypes.NUMBER,
        default: -9007199254740991,
      },
      {
        name: 'step',
        label: '步长',
        type: PropTypes.NUMBER,
        default: 1,
      },
      {
        name: 'resize',
        label: '调整大小',
        type: PropTypes.SELECT,
        default: 'vertical',
        options: [
          { label: '无', value: 'none' },
          { label: '双向', value: 'both' },
          { label: '水平', value: 'horizontal' },
          { label: '垂直', value: 'vertical' },
        ],
      },
      {
        name: 'autofocus',
        label: '自动聚焦',
        type: PropTypes.BOOLEAN,
        default: false,
      },
      {
        name: 'aria-label',
        label: 'ARIA标签',
        type: PropTypes.STRING,
        default: '',
      },
      {
        name: 'tabindex',
        label: 'Tab键顺序',
        type: PropTypes.STRING,
        default: '',
      },
      {
        name: 'validate-event',
        label: '触发校验事件',
        type: PropTypes.BOOLEAN,
        default: true,
      },
      {
        name: 'inputmode',
        label: '输入模式',
        type: PropTypes.STRING,
        default: '',
      },
    ],
    events: [
      { name: 'input', label: '输入事件' },
      { name: 'change', label: '改变事件' },
      { name: 'focus', label: '聚焦事件' },
      { name: 'blur', label: '失焦事件' },
      { name: 'keydown', label: '键盘按下' },
      { name: 'mouseenter', label: '鼠标进入' },
      { name: 'mouseleave', label: '鼠标离开' },
      { name: 'compositionstart', label: '输入法开始' },
      { name: 'compositionupdate', label: '输入法更新' },
      { name: 'compositionend', label: '输入法结束' },
    ],
    slots: [
      { name: 'prepend', label: '前置插槽' },
      { name: 'prefix', label: '前缀插槽' },
      { name: 'suffix', label: '后缀插槽' },
      { name: 'append', label: '后置插槽' },
    ],
    styleConfig: {
      parts: [
        {
          name: 'container',
          label: '根容器',
          styles: ['display', 'width'],
        },
        {
          name: 'prepend',
          label: '前置插槽',
          styles: ['background-color', 'border-color'],
        },
        {
          name: 'inner',
          label: '内部容器',
          styles: ['background-color', 'border-color'],
        },
        {
          name: 'prefix',
          label: '前缀插槽',
          styles: ['color'],
        },
        {
          name: 'original-wrapper',
          label: '输入框包裹',
          styles: ['background-color'],
        },
        {
          name: 'original',
          label: '原生输入框',
          styles: ['color', 'background-color'],
        },
        {
          name: 'suffix',
          label: '后缀插槽',
          styles: ['color'],
        },
        {
          name: 'clear-icon',
          label: '清除图标',
          styles: ['color'],
        },
        {
          name: 'show-password-icon',
          label: '密码图标',
          styles: ['color'],
        },
        {
          name: 'count',
          label: '字数统计',
          styles: ['color'],
        },
        {
          name: 'append',
          label: '后置插槽',
          styles: ['background-color', 'border-color'],
        },
      ],
    },
  },
  {
    type: 'ea-checkbox',
    name: '复选框',
    category: ComponentCategories.FORM,
    icon: 'Checkbox',
    props: [
      {
        name: 'label',
        label: '标签文本',
        type: PropTypes.STRING,
        default: '',
      },
      {
        name: 'value',
        label: '绑定值',
        type: PropTypes.STRING,
        default: '',
      },
      {
        name: 'name',
        label: 'name属性',
        type: PropTypes.STRING,
        default: '',
      },
      {
        name: 'disabled',
        label: '禁用',
        type: PropTypes.BOOLEAN,
        default: false,
      },
      {
        name: 'checked',
        label: '是否选中',
        type: PropTypes.BOOLEAN,
        default: false,
      },
      {
        name: 'indeterminate',
        label: '半选状态',
        type: PropTypes.BOOLEAN,
        default: false,
      },
      {
        name: 'size',
        label: '尺寸',
        type: PropTypes.SELECT,
        default: 'default',
        options: [
          { label: '大', value: 'large' },
          { label: '默认', value: 'default' },
          { label: '小', value: 'small' },
        ],
      },
      {
        name: 'border',
        label: '边框样式',
        type: PropTypes.BOOLEAN,
        default: false,
      },
      {
        name: 'required',
        label: '必填',
        type: PropTypes.BOOLEAN,
        default: false,
      },
    ],
    events: [{ name: 'change', label: '改变事件' }],
    slots: [{ name: 'default', label: '默认插槽' }],
    styleConfig: {
      parts: [
        {
          name: 'container',
          label: '外层容器',
          styles: ['display', 'align-items'],
        },
        {
          name: 'input',
          label: '复选框按钮',
          styles: ['width', 'height', 'background-color', 'border-color'],
        },
        {
          name: 'label',
          label: '标签容器',
          styles: ['color', 'font-size'],
        },
      ],
    },
  },
  {
    type: 'ea-checkbox-group',
    name: '复选框组',
    category: ComponentCategories.FORM,
    icon: 'CheckboxGroup',
    props: [
      {
        name: 'name',
        label: 'name属性',
        type: PropTypes.STRING,
        default: '',
      },
      {
        name: 'value',
        label: '当前选中值',
        type: PropTypes.ARRAY,
        default: [],
      },
      {
        name: 'label',
        label: '标签文本',
        type: PropTypes.STRING,
        default: '',
      },
      {
        name: 'size',
        label: '尺寸',
        type: PropTypes.SELECT,
        default: 'default',
        options: [
          { label: '大', value: 'large' },
          { label: '默认', value: 'default' },
          { label: '小', value: 'small' },
        ],
      },
      {
        name: 'disabled',
        label: '禁用',
        type: PropTypes.BOOLEAN,
        default: false,
      },
      {
        name: 'min',
        label: '最少可选数量',
        type: PropTypes.NUMBER,
        default: 0,
      },
      {
        name: 'max',
        label: '最多可选数量',
        type: PropTypes.NUMBER,
        default: Infinity,
      },
      {
        name: 'required',
        label: '必填',
        type: PropTypes.BOOLEAN,
        default: false,
      },
    ],
    events: [{ name: 'change', label: '改变事件' }],
    slots: [{ name: 'default', label: '复选框插槽', isContentSlot: false }],
    childComponents: ['ea-checkbox'],
    specialConfig: {
      type: 'checkboxGroupOptions',
      propName: 'optionsConfig',
    },
    styleConfig: {
      parts: [
        {
          name: 'container',
          label: '外层容器',
          styles: ['display', 'gap'],
        },
      ],
    },
  },
  {
    type: 'ea-color-picker',
    name: '颜色选择器',
    category: ComponentCategories.FORM,
    icon: 'ColorPicker',
    props: [
      {
        name: 'value',
        label: '绑定值',
        type: PropTypes.STRING,
        default: '',
      },
      {
        name: 'label',
        label: '标签文本',
        type: PropTypes.STRING,
        default: '',
      },
      {
        name: 'disabled',
        label: '禁用',
        type: PropTypes.BOOLEAN,
        default: false,
      },
      {
        name: 'clearable',
        label: '可清空',
        type: PropTypes.BOOLEAN,
        default: true,
      },
      {
        name: 'size',
        label: '尺寸',
        type: PropTypes.SELECT,
        default: '',
        options: [
          { label: '大', value: 'large' },
          { label: '中', value: 'medium' },
          { label: '小', value: 'small' },
        ],
      },
      {
        name: 'color-format',
        label: '颜色格式',
        type: PropTypes.SELECT,
        default: 'hex',
        options: [
          { label: 'HEX', value: 'hex' },
          { label: 'RGB', value: 'rgb' },
          { label: 'HSL', value: 'hsl' },
          { label: 'HSV', value: 'hsv' },
        ],
      },
      {
        name: 'show-alpha',
        label: '支持透明度',
        type: PropTypes.BOOLEAN,
        default: false,
      },
      {
        name: 'tabindex',
        label: 'Tab键顺序',
        type: PropTypes.NUMBER,
        default: 0,
      },
      {
        name: 'placement',
        label: '弹出位置',
        type: PropTypes.SELECT,
        default: 'bottom',
        options: [
          { label: '顶部', value: 'top' },
          { label: '顶部开始', value: 'top-start' },
          { label: '顶部结束', value: 'top-end' },
          { label: '底部', value: 'bottom' },
          { label: '底部开始', value: 'bottom-start' },
          { label: '底部结束', value: 'bottom-end' },
          { label: '左侧', value: 'left' },
          { label: '左侧开始', value: 'left-start' },
          { label: '左侧结束', value: 'left-end' },
          { label: '右侧', value: 'right' },
          { label: '右侧开始', value: 'right-start' },
          { label: '右侧结束', value: 'right-end' },
        ],
      },
      {
        name: 'predefine',
        label: '预定义颜色',
        type: PropTypes.ARRAY,
        default: [],
      },
      {
        name: 'required',
        label: '必填',
        type: PropTypes.BOOLEAN,
        default: false,
      },
    ],
    events: [
      { name: 'change', label: '颜色值改变' },
      { name: 'ea-active-change', label: '颜色激活值改变' },
      { name: 'ea-invalid-color', label: '无效颜色值' },
    ],
    slots: [],
    styleConfig: {
      parts: [
        {
          name: 'container',
          label: '根容器',
          styles: ['display'],
        },
        {
          name: 'trigger',
          label: '触发器',
          styles: ['width', 'height', 'border-color'],
        },
        {
          name: 'outer',
          label: '外层容器',
          styles: ['border-color'],
        },
        {
          name: 'inner',
          label: '内层容器',
          styles: ['background-color'],
        },
      ],
    },
  },
  {
    type: 'ea-color-picker-panel',
    name: '颜色选择器面板',
    category: ComponentCategories.FORM,
    icon: 'ColorPickerPanel',
    props: [
      {
        name: 'value',
        label: '绑定值',
        type: PropTypes.STRING,
        default: '',
      },
      {
        name: 'color-format',
        label: '颜色格式',
        type: PropTypes.SELECT,
        default: 'hex',
        options: [
          { label: 'HEX', value: 'hex' },
          { label: 'RGB', value: 'rgb' },
          { label: 'HSL', value: 'hsl' },
          { label: 'HSV', value: 'hsv' },
        ],
      },
      {
        name: 'show-alpha',
        label: '支持透明度',
        type: PropTypes.BOOLEAN,
        default: false,
      },
      {
        name: 'disabled',
        label: '禁用',
        type: PropTypes.BOOLEAN,
        default: false,
      },
      {
        name: 'border',
        label: '显示边框',
        type: PropTypes.BOOLEAN,
        default: false,
      },
      {
        name: 'clearable',
        label: '可编辑',
        type: PropTypes.BOOLEAN,
        default: true,
      },
      {
        name: 'predefine',
        label: '预定义颜色',
        type: PropTypes.ARRAY,
        default: [],
      },
    ],
    events: [
      { name: 'change', label: '颜色值改变' },
      { name: 'ea-active-change', label: '颜色激活值改变' },
      { name: 'ea-invalid-color', label: '无效颜色值' },
    ],
    slots: [{ name: 'append', label: '附加插槽' }],
    styleConfig: {
      parts: [
        {
          name: 'container',
          label: '容器',
          styles: ['background-color', 'border-color'],
        },
        {
          name: 'svpanel',
          label: '饱和度/亮度面板',
          styles: ['background-color'],
        },
        {
          name: 'hue-slider',
          label: '色调滑块',
          styles: ['background-color'],
        },
        {
          name: 'alpha-slider',
          label: '透明度滑块',
          styles: ['background-color'],
        },
      ],
    },
  },
  {
    type: 'ea-radio',
    name: '单选框',
    category: ComponentCategories.FORM,
    icon: 'Radio',
    props: [
      {
        name: 'name',
        label: '组名',
        type: PropTypes.STRING,
        default: '',
      },
      {
        name: 'value',
        label: '选项值',
        type: PropTypes.STRING,
        default: '',
      },
      {
        name: 'disabled',
        label: '禁用',
        type: PropTypes.BOOLEAN,
        default: false,
      },
      {
        name: 'label',
        label: '标签文本',
        type: PropTypes.STRING,
        default: '',
      },
      {
        name: 'border',
        label: '边框样式',
        type: PropTypes.BOOLEAN,
        default: false,
      },
      {
        name: 'size',
        label: '尺寸',
        type: PropTypes.SELECT,
        default: 'default',
        options: [
          { label: '大', value: 'large' },
          { label: '中', value: 'default' },
          { label: '小', value: 'small' },
        ],
      },
    ],
    events: [{ name: 'change', label: '选中值改变' }],
    slots: [{ name: 'default', label: '选项内容' }],
    styleConfig: {
      parts: [
        {
          name: 'container',
          label: '外层容器',
          styles: ['display', 'align-items'],
        },
        {
          name: 'input-wrap',
          label: '输入框容器',
          styles: ['width', 'height'],
        },
        {
          name: 'input',
          label: '输入框',
          styles: ['border-color', 'background-color'],
        },
        {
          name: 'label-wrap',
          label: '标签容器',
          styles: ['color'],
        },
      ],
    },
  },
  {
    type: 'ea-radio-group',
    name: '单选框组',
    category: ComponentCategories.FORM,
    icon: 'RadioGroup',
    props: [
      {
        name: 'name',
        label: '组名',
        type: PropTypes.STRING,
        default: '',
      },
      {
        name: 'value',
        label: '当前选中值',
        type: PropTypes.STRING,
        default: '',
      },
      {
        name: 'label',
        label: '标签文本',
        type: PropTypes.STRING,
        default: '',
      },
      {
        name: 'disabled',
        label: '整体禁用',
        type: PropTypes.BOOLEAN,
        default: false,
      },
      {
        name: 'size',
        label: '尺寸',
        type: PropTypes.SELECT,
        default: 'default',
        options: [
          { label: '大', value: 'large' },
          { label: '中', value: 'default' },
          { label: '小', value: 'small' },
        ],
      },
      {
        name: 'border',
        label: '边框样式',
        type: PropTypes.BOOLEAN,
        default: false,
      },
      {
        name: 'required',
        label: '必填',
        type: PropTypes.BOOLEAN,
        default: false,
      },
    ],
    events: [{ name: 'change', label: '选中值改变' }],
    slots: [{ name: 'default', label: '单选框插槽', isContentSlot: false }],
    childComponents: ['ea-radio'],
    specialConfig: {
      type: 'radioGroupOptions',
      propName: 'optionsConfig',
    },
    styleConfig: {
      parts: [
        {
          name: 'container',
          label: '外层容器',
          styles: ['display', 'gap'],
        },
      ],
    },
  },
  {
    type: 'ea-input-number',
    name: '数字输入框',
    category: ComponentCategories.FORM,
    icon: 'InputNumber',
    props: [
      {
        name: 'value',
        label: '当前值',
        type: PropTypes.NUMBER,
        default: 0,
      },
      {
        name: 'label',
        label: '标签文本',
        type: PropTypes.STRING,
        default: '',
      },
      {
        name: 'value-on-clear',
        label: '清空时值',
        type: PropTypes.NUMBER,
        default: null,
      },
      {
        name: 'min',
        label: '最小值',
        type: PropTypes.NUMBER,
        default: -9007199254740991,
      },
      {
        name: 'max',
        label: '最大值',
        type: PropTypes.NUMBER,
        default: 9007199254740991,
      },
      {
        name: 'step',
        label: '步长',
        type: PropTypes.NUMBER,
        default: 1,
      },
      {
        name: 'step-strictly',
        label: '严格步长',
        type: PropTypes.BOOLEAN,
        default: false,
      },
      {
        name: 'precision',
        label: '小数精度',
        type: PropTypes.NUMBER,
        default: null,
      },
      {
        name: 'size',
        label: '尺寸',
        type: PropTypes.SELECT,
        default: 'default',
        options: [
          { label: '大', value: 'large' },
          { label: '中', value: 'default' },
          { label: '小', value: 'small' },
        ],
      },
      {
        name: 'readonly',
        label: '只读',
        type: PropTypes.BOOLEAN,
        default: false,
      },
      {
        name: 'disabled',
        label: '禁用',
        type: PropTypes.BOOLEAN,
        default: false,
      },
      {
        name: 'controls',
        label: '控制按钮',
        type: PropTypes.BOOLEAN,
        default: true,
      },
      {
        name: 'align',
        label: '对齐方式',
        type: PropTypes.SELECT,
        default: 'center',
        options: [
          { label: '左对齐', value: 'left' },
          { label: '居中', value: 'center' },
          { label: '右对齐', value: 'right' },
        ],
      },
      {
        name: 'name',
        label: 'name属性',
        type: PropTypes.STRING,
        default: '',
      },
      {
        name: 'placeholder',
        label: '占位符',
        type: PropTypes.STRING,
        default: '',
      },
      {
        name: 'inputmode',
        label: '输入模式',
        type: PropTypes.STRING,
        default: '',
      },
      {
        name: 'required',
        label: '必填',
        type: PropTypes.BOOLEAN,
        default: false,
      },
    ],
    events: [
      { name: 'ea-change', label: '值改变' },
      { name: 'blur', label: '失焦' },
      { name: 'focus', label: '聚焦' },
    ],
    slots: [
      { name: 'prefix', label: '前缀插槽' },
      { name: 'suffix', label: '后缀插槽' },
    ],
    styleConfig: {
      parts: [
        {
          name: 'container',
          label: '根容器',
          styles: ['display', 'width'],
        },
        {
          name: 'decrease',
          label: '减号按钮',
          styles: ['background-color', 'color'],
        },
        {
          name: 'prefix',
          label: '前缀插槽',
          styles: ['color'],
        },
        {
          name: 'input',
          label: '输入框',
          styles: ['color', 'background-color'],
        },
        {
          name: 'suffix',
          label: '后缀插槽',
          styles: ['color'],
        },
        {
          name: 'increase',
          label: '加号按钮',
          styles: ['background-color', 'color'],
        },
      ],
    },
  },
  {
    type: 'ea-select',
    name: '选择器',
    category: ComponentCategories.FORM,
    icon: 'Select',
    props: [
      {
        name: 'name',
        label: 'name属性',
        type: PropTypes.STRING,
        default: '',
      },
      {
        name: 'value',
        label: '选中值',
        type: PropTypes.STRING,
        default: '',
      },
      {
        name: 'placeholder',
        label: '占位符',
        type: PropTypes.STRING,
        default: '',
      },
      {
        name: 'disabled',
        label: '禁用',
        type: PropTypes.BOOLEAN,
        default: false,
      },
      {
        name: 'clearable',
        label: '可清空',
        type: PropTypes.BOOLEAN,
        default: false,
      },
      {
        name: 'size',
        label: '尺寸',
        type: PropTypes.SELECT,
        default: '',
        options: [
          { label: '大', value: 'large' },
          { label: '中', value: 'default' },
          { label: '小', value: 'small' },
        ],
      },
      {
        name: 'multiple',
        label: '多选',
        type: PropTypes.BOOLEAN,
        default: false,
      },
      {
        name: 'collapse-tags',
        label: '折叠标签',
        type: PropTypes.BOOLEAN,
        default: false,
      },
      {
        name: 'max-collapse-tags',
        label: '最大折叠标签数',
        type: PropTypes.NUMBER,
        default: 1,
      },
      {
        name: 'filterable',
        label: '可搜索',
        type: PropTypes.BOOLEAN,
        default: false,
      },
    ],
    events: [
      { name: 'change', label: '选中值改变' },
      { name: 'ea-clear', label: '清空' },
      { name: 'ea-visible-change', label: '下拉显示改变' },
      { name: 'ea-remove-tag', label: '移除标签' },
    ],
    slots: [{ name: 'default', label: '选项插槽' }],
    styleConfig: {
      parts: [
        {
          name: 'container',
          label: '外层容器',
          styles: ['display', 'width'],
        },
        {
          name: 'input',
          label: '输入框',
          styles: ['background-color', 'border-color'],
        },
        {
          name: 'tag-wrap',
          label: '标签容器',
          styles: ['background-color'],
        },
        {
          name: 'clear-icon',
          label: '清除图标',
          styles: ['color'],
        },
        {
          name: 'dropdown-icon',
          label: '下拉图标',
          styles: ['color'],
        },
        {
          name: 'dropdown',
          label: '下拉框',
          styles: ['background-color', 'border-color'],
        },
      ],
    },
    childComponents: ['ea-option', 'ea-option-group'],
    specialConfig: {
      type: 'selectOptions',
      propName: 'optionsConfig',
    },
  },

  {
    type: 'ea-switch',
    name: '开关',
    category: ComponentCategories.FORM,
    icon: 'Switch',
    props: [
      {
        name: 'name',
        label: 'name属性',
        type: PropTypes.STRING,
        default: '',
      },
      {
        name: 'value',
        label: '当前值',
        type: PropTypes.STRING,
        default: 'false',
      },
      {
        name: 'label',
        label: '标签文本',
        type: PropTypes.STRING,
        default: '',
      },
      {
        name: 'active-value',
        label: '开启值',
        type: PropTypes.STRING,
        default: 'true',
      },
      {
        name: 'inactive-value',
        label: '关闭值',
        type: PropTypes.STRING,
        default: 'false',
      },
      {
        name: 'size',
        label: '尺寸',
        type: PropTypes.SELECT,
        default: 'default',
        options: [
          { label: '大', value: 'large' },
          { label: '中', value: 'default' },
          { label: '小', value: 'small' },
        ],
      },
      {
        name: 'inactive-text',
        label: '关闭文本',
        type: PropTypes.STRING,
        default: '',
      },
      {
        name: 'inactive-color',
        label: '关闭颜色',
        type: PropTypes.STRING,
        default: '',
      },
      {
        name: 'active-text',
        label: '开启文本',
        type: PropTypes.STRING,
        default: '',
      },
      {
        name: 'active-color',
        label: '开启颜色',
        type: PropTypes.STRING,
        default: '',
      },
      {
        name: 'disabled',
        label: '禁用',
        type: PropTypes.BOOLEAN,
        default: false,
      },
      {
        name: 'required',
        label: '必填',
        type: PropTypes.BOOLEAN,
        default: false,
      },
    ],
    events: [{ name: 'change', label: '状态改变' }],
    slots: [
      { name: 'active', label: '开启插槽' },
      { name: 'inactive', label: '关闭插槽' },
    ],
    styleConfig: {
      parts: [
        {
          name: 'container',
          label: '外层容器',
          styles: ['display', 'align-items'],
        },
        {
          name: 'original',
          label: '原生控件',
          styles: ['display'],
        },
        {
          name: 'label-left',
          label: '左侧文字',
          styles: ['color'],
        },
        {
          name: 'switch',
          label: '开关控件',
          styles: ['background-color', 'border-color'],
        },
        {
          name: 'label-right',
          label: '右侧文字',
          styles: ['color'],
        },
      ],
    },
  },
  {
    type: 'ea-slider',
    name: '滑块',
    category: ComponentCategories.FORM,
    icon: 'Slider',
    props: [
      {
        name: 'value',
        label: '绑定值',
        type: PropTypes.NUMBER,
        default: 0,
      },
      {
        name: 'label',
        label: '标签文本',
        type: PropTypes.STRING,
        default: '',
      },
      {
        name: 'min',
        label: '最小值',
        type: PropTypes.NUMBER,
        default: 0,
      },
      {
        name: 'max',
        label: '最大值',
        type: PropTypes.NUMBER,
        default: 100,
      },
      {
        name: 'step',
        label: '步长',
        type: PropTypes.NUMBER,
        default: 1,
      },
      {
        name: 'disabled',
        label: '禁用',
        type: PropTypes.BOOLEAN,
        default: false,
      },
      {
        name: 'vertical',
        label: '垂直模式',
        type: PropTypes.BOOLEAN,
        default: false,
      },
      {
        name: 'show-input',
        label: '显示输入框',
        type: PropTypes.BOOLEAN,
        default: false,
      },
      {
        name: 'show-tooltip',
        label: '显示提示',
        type: PropTypes.BOOLEAN,
        default: true,
      },
      {
        name: 'show-stops',
        label: '显示步长节点',
        type: PropTypes.BOOLEAN,
        default: false,
      },
      {
        name: 'placement',
        label: '提示位置',
        type: PropTypes.SELECT,
        default: 'top',
        options: [
          { label: '顶部', value: 'top' },
          { label: '顶部开始', value: 'top-start' },
          { label: '顶部结束', value: 'top-end' },
          { label: '底部', value: 'bottom' },
          { label: '底部开始', value: 'bottom-start' },
          { label: '底部结束', value: 'bottom-end' },
          { label: '左侧', value: 'left' },
          { label: '左侧开始', value: 'left-start' },
          { label: '左侧结束', value: 'left-end' },
          { label: '右侧', value: 'right' },
          { label: '右侧开始', value: 'right-start' },
          { label: '右侧结束', value: 'right-end' },
        ],
      },
      {
        name: 'size',
        label: '尺寸',
        type: PropTypes.SELECT,
        default: '',
        options: [
          { label: '大', value: 'large' },
          { label: '中', value: 'default' },
          { label: '小', value: 'small' },
        ],
      },
      {
        name: 'required',
        label: '必填',
        type: PropTypes.BOOLEAN,
        default: false,
      },
    ],
    events: [
      { name: 'change', label: '值改变' },
      { name: 'input', label: '拖动中' },
    ],
    slots: [],
    styleConfig: {
      parts: [
        {
          name: 'container',
          label: '根容器',
          styles: ['display', 'width'],
        },
        {
          name: 'runway',
          label: '轨道容器',
          styles: ['background-color'],
        },
        {
          name: 'rail',
          label: '轨道',
          styles: ['background-color'],
        },
        {
          name: 'stop',
          label: '步长节点',
          styles: ['background-color'],
        },
        {
          name: 'trigger',
          label: '触发器',
          styles: ['display'],
        },
        {
          name: 'thumb',
          label: '滑块按钮',
          styles: ['background-color', 'border-color'],
        },
        {
          name: 'tooltip',
          label: '提示框',
          styles: ['color', 'background-color'],
        },
        {
          name: 'input',
          label: '输入框',
          styles: ['width'],
        },
      ],
    },
  },
  {
    type: 'ea-date-picker',
    name: '日期选择器',
    category: ComponentCategories.FORM,
    icon: 'DatePicker',
    props: [
      {
        name: 'value',
        label: '日期值',
        type: PropTypes.STRING,
        default: '',
      },
      {
        name: 'label',
        label: '标签文本',
        type: PropTypes.STRING,
        default: '',
      },
      {
        name: 'type',
        label: '显示类型',
        type: PropTypes.SELECT,
        default: 'date',
        options: [
          { label: '日期', value: 'date' },
          { label: '月份', value: 'month' },
          { label: '年份', value: 'year' },
        ],
      },
      {
        name: 'placeholder',
        label: '占位符',
        type: PropTypes.STRING,
        default: '',
      },
      {
        name: 'disabled',
        label: '禁用',
        type: PropTypes.BOOLEAN,
        default: false,
      },
      {
        name: 'size',
        label: '尺寸',
        type: PropTypes.SELECT,
        default: 'default',
        options: [
          { label: '大', value: 'large' },
          { label: '中', value: 'default' },
          { label: '小', value: 'small' },
        ],
      },
      {
        name: 'align',
        label: '对齐方式',
        type: PropTypes.SELECT,
        default: 'left',
        options: [
          { label: '左对齐', value: 'left' },
          { label: '居中', value: 'center' },
          { label: '右对齐', value: 'right' },
        ],
      },
      {
        name: 'display-format',
        label: '显示格式',
        type: PropTypes.STRING,
        default: 'YYYY-MM-DD',
      },
      {
        name: 'value-format',
        label: '值格式',
        type: PropTypes.STRING,
        default: 'YYYY-MM-DD',
      },
      {
        name: 'width',
        label: '宽度',
        type: PropTypes.STRING,
        default: '',
      },
      {
        name: 'locale',
        label: '语言',
        type: PropTypes.STRING,
        default: 'en-US',
      },
      {
        name: 'required',
        label: '必填',
        type: PropTypes.BOOLEAN,
        default: false,
      },
    ],
    events: [
      { name: 'change', label: '日期改变' },
      { name: 'focus', label: '聚焦' },
      { name: 'blur', label: '失焦' },
      { name: 'ea-panel-change', label: '面板改变' },
      { name: 'ea-visible-change', label: '显示状态改变' },
    ],
    slots: [],
    styleConfig: {
      parts: [
        {
          name: 'container',
          label: '根容器',
          styles: ['display', 'width'],
        },
        {
          name: 'input-wrap',
          label: '输入框包装器',
          styles: ['background-color', 'border-color'],
        },
        {
          name: 'input',
          label: '输入框',
          styles: ['color'],
        },
        {
          name: 'dropdown-wrap',
          label: '下拉面板包装器',
          styles: ['background-color', 'border-color'],
        },
        {
          name: 'calendar-header',
          label: '日历头部',
          styles: ['background-color'],
        },
        {
          name: 'calendar-body',
          label: '日历主体',
          styles: ['background-color'],
        },
      ],
    },
  },
  {
    type: 'ea-time-picker',
    name: '时间选择器',
    category: ComponentCategories.FORM,
    icon: 'TimePicker',
    props: [
      {
        name: 'value',
        label: '时间值',
        type: PropTypes.STRING,
        default: '',
      },
      {
        name: 'label',
        label: '标签文本',
        type: PropTypes.STRING,
        default: '',
      },
      {
        name: 'width',
        label: '宽度',
        type: PropTypes.STRING,
        default: '',
      },
      {
        name: 'disabled',
        label: '禁用',
        type: PropTypes.BOOLEAN,
        default: false,
      },
      {
        name: 'align',
        label: '对齐方式',
        type: PropTypes.SELECT,
        default: 'left',
        options: [
          { label: '左对齐', value: 'left' },
          { label: '居中', value: 'center' },
          { label: '右对齐', value: 'right' },
        ],
      },
      {
        name: 'placeholder',
        label: '占位符',
        type: PropTypes.STRING,
        default: '',
      },
      {
        name: 'limit-range-start',
        label: '限制开始时间',
        type: PropTypes.STRING,
        default: '00:00:00',
      },
      {
        name: 'limit-range-end',
        label: '限制结束时间',
        type: PropTypes.STRING,
        default: '23:59:59',
      },
      {
        name: 'required',
        label: '必填',
        type: PropTypes.BOOLEAN,
        default: false,
      },
    ],
    events: [{ name: 'change', label: '时间改变' }],
    slots: [],
    styleConfig: {
      parts: [
        {
          name: 'container',
          label: '组件容器',
          styles: ['display', 'width'],
        },
        {
          name: 'input',
          label: '输入框元素',
          styles: ['background-color', 'border-color'],
        },
        {
          name: 'dropdown',
          label: '下拉面板',
          styles: ['background-color', 'border-color'],
        },
        {
          name: 'dropdown-inner-wrap',
          label: '下拉内部容器',
          styles: ['background-color'],
        },
        {
          name: 'dropdown-time',
          label: '时间列表',
          styles: ['background-color'],
        },
        {
          name: 'dropdown-item',
          label: '时间项',
          styles: ['color', 'background-color'],
        },
      ],
    },
  },
  {
    type: 'ea-rate',
    name: '评分',
    category: ComponentCategories.FORM,
    icon: 'Rate',
    props: [
      {
        name: 'value',
        label: '当前评分',
        type: PropTypes.NUMBER,
        default: 0,
      },
      {
        name: 'label',
        label: '标签文本',
        type: PropTypes.STRING,
        default: '',
      },
      {
        name: 'max',
        label: '最大评分',
        type: PropTypes.NUMBER,
        default: 5,
      },
      {
        name: 'size',
        label: '尺寸',
        type: PropTypes.SELECT,
        default: '',
        options: [
          { label: '大', value: 'large' },
          { label: '中', value: 'default' },
          { label: '小', value: 'small' },
        ],
      },
      {
        name: 'readonly',
        label: '只读',
        type: PropTypes.BOOLEAN,
        default: false,
      },
      {
        name: 'disabled',
        label: '禁用',
        type: PropTypes.BOOLEAN,
        default: false,
      },
      {
        name: 'required',
        label: '必填',
        type: PropTypes.BOOLEAN,
        default: false,
      },
    ],
    events: [
      { name: 'change', label: '评分改变' },
      { name: 'hover', label: '悬停' },
    ],
    slots: [],
    styleConfig: {
      parts: [
        {
          name: 'container',
          label: '外层容器',
          styles: ['display', 'gap'],
        },
      ],
    },
  },
  {
    type: 'ea-transfer',
    name: '穿梭框',
    category: ComponentCategories.FORM,
    icon: 'Transfer',
    props: [
      {
        name: 'data',
        label: '数据源',
        type: PropTypes.ARRAY,
        default: [],
      },
      {
        name: 'value',
        label: '选中值',
        type: PropTypes.ARRAY,
        default: [],
      },
      {
        name: 'label',
        label: '标签文本',
        type: PropTypes.STRING,
        default: '',
      },
      {
        name: 'disabled',
        label: '禁用',
        type: PropTypes.BOOLEAN,
        default: false,
      },
      {
        name: 'filterable',
        label: '可搜索',
        type: PropTypes.BOOLEAN,
        default: false,
      },
      {
        name: 'filter-placeholder',
        label: '搜索占位符',
        type: PropTypes.STRING,
        default: '请输入搜索内容',
      },
      {
        name: 'titles',
        label: '面板标题',
        type: PropTypes.ARRAY,
        default: [],
      },
      {
        name: 'button-texts',
        label: '按钮文本',
        type: PropTypes.ARRAY,
        default: [],
      },
      {
        name: 'required',
        label: '必填',
        type: PropTypes.BOOLEAN,
        default: false,
      },
    ],
    events: [
      { name: 'change', label: '选中项改变' },
      { name: 'ea-left-check-change', label: '左侧选中改变' },
      { name: 'ea-right-check-change', label: '右侧选中改变' },
    ],
    slots: [
      { name: 'left-empty', label: '左侧空状态' },
      { name: 'right-empty', label: '右侧空状态' },
      { name: 'left-footer', label: '左侧底部' },
      { name: 'right-footer', label: '右侧底部' },
    ],
    styleConfig: {
      parts: [
        {
          name: 'container',
          label: '组件容器',
          styles: ['display', 'gap'],
        },
        {
          name: 'panel',
          label: '面板容器',
          styles: ['background-color', 'border-color'],
        },
        {
          name: 'buttons',
          label: '按钮区域',
          styles: ['display', 'gap'],
        },
        {
          name: 'button',
          label: '按钮',
          styles: ['background-color', 'color'],
        },
      ],
    },
  },
  // Select 专用子组件
  {
    type: 'ea-option',
    name: '选项',
    category: ComponentCategories.FORM,
    icon: 'Option',
    isChildComponent: true,
    parentComponents: ['ea-select'],
    props: [
      {
        name: 'value',
        label: '选项值',
        type: PropTypes.STRING,
        default: '',
      },
      {
        name: 'label',
        label: '显示文本',
        type: PropTypes.STRING,
        default: '',
      },
      {
        name: 'disabled',
        label: '禁用',
        type: PropTypes.BOOLEAN,
        default: false,
      },
    ],
    events: [],
    slots: [{ name: 'default', label: '选项内容' }],
  },
  {
    type: 'ea-option-group',
    name: '选项分组',
    category: ComponentCategories.FORM,
    icon: 'OptionGroup',
    isChildComponent: true,
    parentComponents: ['ea-select'],
    props: [
      {
        name: 'label',
        label: '分组标签',
        type: PropTypes.STRING,
        default: '',
      },
    ],
    events: [],
    slots: [
      { name: 'default', label: '选项内容' },
      { name: 'header', label: '头部插槽' },
    ],
    childComponents: ['ea-option'],
  },
]
